#!/usr/bin/env node

'use strict';

const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const {
  GENERATOR_VERSION,
  TARGET_ROOTS,
  compilePlans,
  inventoryFor
} = require('../bin/lib/adapter-compiler');

const ROOT = path.resolve(__dirname, '..');
const BUILD = path.join(ROOT, 'scripts', 'build-adapters.js');
const PACKAGE_VERSION = require('../package.json').version;
const GENERATED_BANNER = `Generated by WTF-P adapter compiler v${GENERATOR_VERSION}`;

const EXPECTED_ROOTS = Object.freeze({
  antigravity: path.join(ROOT, 'vendors', 'antigravity'),
  claude: path.join(ROOT, 'vendors', 'claude'),
  clio: path.join(ROOT, 'vendors', 'clio'),
  codex: path.join(ROOT, 'vendors', 'codex', 'plugins', 'wtf-p'),
  copilot: path.join(ROOT, 'vendors', 'copilot', 'plugins', 'wtf-p'),
  gemini: path.join(ROOT, 'vendors', 'gemini'),
  opencode: path.join(ROOT, 'vendors', 'opencode')
});

const EXPECTED_SKILLS = [
  'wtfp-deliver-research',
  'wtfp-manage-project',
  'wtfp-plan-section',
  'wtfp-research-literature',
  'wtfp-review-manuscript',
  'wtfp-start-project',
  'wtfp-write-section'
];

const EXPECTED_ROLES = [
  'argument-verifier',
  'citation-expert',
  'citation-formatter',
  'coherence-checker',
  'outliner',
  'plan-checker',
  'prose-polisher',
  'research-synthesizer',
  'section-planner',
  'section-reviewer',
  'section-writer'
];

const CLIO_ROLE_SKILLS = Object.freeze({
  'argument-verifier': 'wtfp-review-manuscript',
  'citation-expert': 'wtfp-research-literature',
  'citation-formatter': 'wtfp-research-literature',
  'coherence-checker': 'wtfp-review-manuscript',
  'outliner': 'wtfp-start-project',
  'plan-checker': 'wtfp-plan-section',
  'prose-polisher': 'wtfp-review-manuscript',
  'research-synthesizer': 'wtfp-research-literature',
  'section-planner': 'wtfp-plan-section',
  'section-reviewer': 'wtfp-review-manuscript',
  'section-writer': 'wtfp-write-section'
});

const failures = [];
let passed = 0;

function record(name, test) {
  try {
    test();
    passed++;
    process.stdout.write(`\x1b[32m✓\x1b[0m ${name}\n`);
  } catch (error) {
    failures.push({ name, error });
    process.stderr.write(`\x1b[31m✗\x1b[0m ${name}\n${error.stack || error.message}\n`);
  }
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function sha256(content) {
  return crypto.createHash('sha256').update(content).digest('hex');
}

function posix(value) {
  return value.split(path.sep).join('/');
}

function sorted(values) {
  return [...values].sort((left, right) => left.localeCompare(right));
}

function planFiles(plan, pattern) {
  return sorted([...plan.files.keys()].filter((file) => pattern.test(file)));
}

function planText(plan, relativePath) {
  const content = plan.files.get(relativePath);
  assert.ok(content, `${plan.id}: missing generated file ${relativePath}`);
  return content.toString('utf8');
}

function assertDirectory(plan, relativePath, context) {
  const prefix = `${relativePath.replace(/\/$/, '')}/`;
  assert.ok(
    [...plan.files.keys()].some((file) => file.startsWith(prefix)),
    `${plan.id}: ${context} points at missing directory ${relativePath}`
  );
}

function assertManifestDirectory(plan, reference, context) {
  assert.match(reference, /^\.\/[a-z][a-z0-9-]*\/?$/, `${plan.id}: unsafe ${context} path ${reference}`);
  assertDirectory(plan, reference.replace(/^\.\//, ''), context);
}

function commandPaths(target, actionIds) {
  if (target === 'clio') return actionIds.map((id) => `prompts/wtfp/${id}.md`);
  if (target === 'claude') return actionIds.map((id) => `commands/${id}.md`);
  if (target === 'gemini') return actionIds.map((id) => `commands/wtfp/${id}.toml`);
  if (target === 'copilot' || target === 'antigravity') {
    return actionIds.map((id) => `commands/wtfp-${id}.md`);
  }
  return actionIds.map((id) => `commands/wtfp/${id}.md`);
}

function expectedAgentPaths(target) {
  if (['clio', 'copilot', 'antigravity'].includes(target)) {
    return EXPECTED_ROLES.map((role) => `agents/wtfp-${role}.md`);
  }
  return EXPECTED_ROLES.map((role) => `agents/wtfp/${role}.md`);
}

function planFingerprint(plans) {
  return plans.map((plan) => ({
    id: plan.id,
    root: plan.root,
    inventory: inventoryFor(plan)
  }));
}

function snapshotInventories(plans) {
  return new Map(plans.map((plan) => {
    const inventoryPath = path.join(plan.root, '.wtfp-generated.json');
    return [inventoryPath, fs.readFileSync(inventoryPath)];
  }));
}

function isolatedEnvironment(root) {
  const home = path.join(root, 'home');
  return {
    ...process.env,
    HOME: home,
    USERPROFILE: home,
    XDG_CONFIG_HOME: path.join(root, 'xdg', 'config'),
    XDG_DATA_HOME: path.join(root, 'xdg', 'data'),
    XDG_STATE_HOME: path.join(root, 'xdg', 'state'),
    XDG_CACHE_HOME: path.join(root, 'xdg', 'cache'),
    CLAUDE_CONFIG_DIR: path.join(root, 'clients', 'claude'),
    CLIO_CODER_CONFIG_DIR: path.join(root, 'clients', 'clio'),
    CODEX_HOME: path.join(root, 'clients', 'codex'),
    COPILOT_HOME: path.join(root, 'clients', 'copilot'),
    GEMINI_CLI_HOME: path.join(root, 'clients', 'gemini'),
    OPENCODE_CONFIG_DIR: path.join(root, 'clients', 'opencode'),
    ANTIGRAVITY_HOME: path.join(root, 'clients', 'antigravity'),
    FORCE_COLOR: '',
    NO_COLOR: '1'
  };
}

function runCheck(cwd, environment) {
  return spawnSync(process.execPath, [BUILD, '--check'], {
    cwd,
    env: environment,
    encoding: 'utf8',
    input: '',
    timeout: 30000
  });
}

function copyCompilerFixture(destination) {
  const copies = [
    ['bin/lib', 'bin/lib'],
    ['protocol', 'protocol']
  ];
  for (const [source, target] of copies) {
    fs.cpSync(path.join(ROOT, source), path.join(destination, target), { recursive: true });
  }
  for (const file of ['CONTRIBUTING.md', 'package.json']) {
    fs.mkdirSync(path.dirname(path.join(destination, file)), { recursive: true });
    fs.copyFileSync(path.join(ROOT, file), path.join(destination, file));
  }
}

function assertCheckSuccess(result, context) {
  assert.ifError(result.error);
  assert.strictEqual(result.signal, null, `${context}: terminated by ${result.signal}`);
  assert.strictEqual(result.status, 0, `${context}\n${result.stdout || ''}${result.stderr || ''}`);
  assert.strictEqual(result.stderr, '', `${context}: wrote unexpected stderr`);
  assert.match(result.stdout, /^Generated adapters are current \(\d+ envelopes\)\.\n$/);
}

function staticReferenceCandidates(reference) {
  const candidates = [reference];
  if (/[.,;:!?]$/.test(reference)) candidates.push(reference.slice(0, -1));
  return candidates;
}

function assertBundleReference(plan, reference, sourcePath) {
  for (const candidate of staticReferenceCandidates(reference)) {
    assert.ok(!path.posix.isAbsolute(candidate), `${plan.id}:${sourcePath}: absolute bundle reference ${candidate}`);
    assert.ok(!candidate.split('/').includes('..'), `${plan.id}:${sourcePath}: traversing bundle reference ${candidate}`);

    const dynamicAt = candidate.search(/[{}*]/);
    if (dynamicAt !== -1) {
      const staticPrefix = candidate.slice(0, dynamicAt);
      if ([...plan.files.keys()].some((file) => file.startsWith(staticPrefix))) return;
      continue;
    }
    if (plan.files.has(candidate)) return;
    if ([...plan.files.keys()].some((file) => file.startsWith(`${candidate.replace(/\/$/, '')}/`))) return;
  }
  assert.fail(`${plan.id}:${sourcePath}: bundle reference does not resolve inside its envelope: ${reference}`);
}

function assertSelfContained(plan, nativePaths, transformProtocolReferences) {
  let references = 0;
  for (const sourcePath of nativePaths) {
    const source = planText(plan, sourcePath);
    const logical = /protocol:\/\/([A-Za-z0-9._{}*/-]+)/g;
    const rooted = /\$\{(?:extensionRoot|extensionPath|CLAUDE_PLUGIN_ROOT|PLUGIN_ROOT)\}\/([A-Za-z0-9._{}*/-]+)/g;
    for (const pattern of [logical, rooted]) {
      for (const match of source.matchAll(pattern)) {
        references++;
        assertBundleReference(plan, match[1], sourcePath);
      }
    }
    assert.doesNotMatch(source, /^@protocol:\/\//m, `${plan.id}:${sourcePath}: unresolved protocol include`);
    if (transformProtocolReferences) {
      assert.doesNotMatch(
        source,
        /protocol:\/\//,
        `${plan.id}:${sourcePath}: a native bundle reference was not rewritten`
      );
    }
  }
  assert.ok(references > 0, `${plan.id}: no bundle references were checked`);
}

function assertSkillLinksResolve(plan) {
  for (const sourcePath of planFiles(plan, /^skills\/[^/]+\/.*\.md$/)) {
    const source = planText(plan, sourcePath);
    for (const match of source.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) {
      const reference = match[1].split('#')[0];
      if (!reference || /^[a-z][a-z0-9+.-]*:/i.test(reference) || reference.startsWith('/')) continue;
      const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(sourcePath), reference));
      assert.ok(!resolved.startsWith('../'), `${plan.id}:${sourcePath}: link escapes the bundle: ${reference}`);
      assert.ok(plan.files.has(resolved), `${plan.id}:${sourcePath}: broken bundled link ${reference}`);
    }
  }
}

const firstPlans = compilePlans();
const plansById = new Map(firstPlans.map((plan) => [plan.id, plan]));
const aliases = readJson(path.join(ROOT, 'protocol', 'aliases.lock.json')).aliases;
const actionIds = aliases.map((entry) => entry.action);
const toolsRegistry = readJson(path.join(ROOT, 'protocol', 'tools.json')).tools;

record('compiler plans and target roots are exact and deterministic', () => {
  assert.deepStrictEqual(TARGET_ROOTS, EXPECTED_ROOTS);
  assert.deepStrictEqual(
    firstPlans.map((plan) => [plan.id, plan.root]),
    [
      ['clio', EXPECTED_ROOTS.clio],
      ['claude', EXPECTED_ROOTS.claude],
      ['codex', EXPECTED_ROOTS.codex],
      ['copilot', EXPECTED_ROOTS.copilot],
      ['opencode', EXPECTED_ROOTS.opencode],
      ['antigravity', EXPECTED_ROOTS.antigravity],
      ['gemini', EXPECTED_ROOTS.gemini],
      ['codex-marketplace', path.join(ROOT, 'vendors', 'codex')],
      ['copilot-marketplace', path.join(ROOT, 'vendors', 'copilot')]
    ]
  );
  assert.deepStrictEqual(planFingerprint(compilePlans()), planFingerprint(firstPlans));
});

record('generated inventories exactly authenticate every compiler-owned file', () => {
  for (const plan of firstPlans) {
    const inventoryPath = path.join(plan.root, '.wtfp-generated.json');
    const inventory = readJson(inventoryPath);
    assert.deepStrictEqual(inventory, inventoryFor(plan), `${plan.id}: stale or nondeterministic inventory`);
    assert.strictEqual(inventory.schema, 'wtfp.generated-adapter/v1');
    assert.strictEqual(inventory.target, plan.id);
    assert.deepStrictEqual(inventory.files.map((file) => file.path), sorted(plan.files.keys()));
    for (const file of inventory.files) {
      assert.match(file.sha256, /^[a-f0-9]{64}$/);
      assert.ok(!path.posix.isAbsolute(file.path), `${plan.id}: inventory contains an absolute path`);
      assert.ok(!file.path.split('/').includes('..'), `${plan.id}: inventory path traverses its root`);
      const actual = fs.readFileSync(path.join(plan.root, file.path));
      assert.strictEqual(sha256(actual), file.sha256, `${plan.id}: generated file hash drift: ${file.path}`);
    }
  }
});

record('real --check is read-only and emits identical results from an isolated home', () => {
  const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'wtfp-adapter-check-'));
  try {
    const before = snapshotInventories(firstPlans);
    const environment = isolatedEnvironment(temporaryRoot);
    const first = runCheck(temporaryRoot, environment);
    const second = runCheck(temporaryRoot, environment);
    assertCheckSuccess(first, 'first adapter --check');
    assertCheckSuccess(second, 'second adapter --check');
    assert.strictEqual(second.stdout, first.stdout, '--check output is not deterministic');
    assert.strictEqual(second.stderr, first.stderr, '--check diagnostics are not deterministic');
    for (const [inventoryPath, content] of before) {
      assert.deepStrictEqual(fs.readFileSync(inventoryPath), content, `--check mutated ${inventoryPath}`);
    }
    assert.deepStrictEqual(
      fs.readdirSync(temporaryRoot).sort(),
      [],
      '--check created state in its isolated working directory or home'
    );
  } finally {
    fs.rmSync(temporaryRoot, { recursive: true, force: true });
  }
});

record('stale inventory cleanup is exact, read-only in check mode, and fail-closed', () => {
  const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'wtfp-adapter-stale-'));
  try {
    copyCompilerFixture(temporaryRoot);
    const isolatedCompilerPath = path.join(temporaryRoot, 'bin', 'lib', 'adapter-compiler.js');
    const isolatedCompiler = require(isolatedCompilerPath);
    isolatedCompiler.compileAdapters();

    const clioRoot = isolatedCompiler.TARGET_ROOTS.clio;
    const inventoryPath = path.join(clioRoot, '.wtfp-generated.json');
    const staleEmpty = 'retired/empty/compiler-owned.md';
    const staleShared = 'retired/shared/compiler-owned.md';
    const userSibling = path.join(clioRoot, 'retired', 'shared', 'user-owned.md');
    for (const relativePath of [staleEmpty, staleShared]) {
      const absolutePath = path.join(clioRoot, relativePath);
      fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
      fs.writeFileSync(absolutePath, 'stale compiler output\n');
    }
    fs.writeFileSync(userSibling, 'must survive cleanup\n');

    const priorInventory = readJson(inventoryPath);
    priorInventory.files.push(
      { path: staleEmpty, sha256: sha256('stale compiler output\n') },
      { path: staleShared, sha256: sha256('stale compiler output\n') }
    );
    priorInventory.files.sort((left, right) => left.path.localeCompare(right.path));
    fs.writeFileSync(inventoryPath, `${JSON.stringify(priorInventory, null, 2)}\n`);
    const inventoryBeforeCheck = fs.readFileSync(inventoryPath);

    assert.throws(
      () => isolatedCompiler.compileAdapters({ check: true }),
      (error) => /generated adapters are stale/.test(error.message)
        && error.message.includes(`stale:${staleEmpty}`)
        && error.message.includes(`stale:${staleShared}`),
      'check mode did not report both stale owned paths'
    );
    assert.deepStrictEqual(fs.readFileSync(inventoryPath), inventoryBeforeCheck, 'check mode rewrote the prior inventory');
    assert.ok(fs.existsSync(path.join(clioRoot, staleEmpty)), 'check mode removed a stale file');
    assert.ok(fs.existsSync(path.join(clioRoot, staleShared)), 'check mode removed a stale shared file');

    const result = isolatedCompiler.compileAdapters();
    const clioChanges = result.changed.find((entry) => entry.target === 'clio');
    assert.ok(clioChanges, 'build omitted the changed Clio target');
    assert.ok(clioChanges.files.includes(`stale:${staleEmpty}`));
    assert.ok(clioChanges.files.includes(`stale:${staleShared}`));
    assert.strictEqual(fs.existsSync(path.join(clioRoot, staleEmpty)), false, 'stale owned file survived regeneration');
    assert.strictEqual(fs.existsSync(path.join(clioRoot, 'retired', 'empty')), false, 'empty stale directory survived regeneration');
    assert.strictEqual(fs.existsSync(path.join(clioRoot, staleShared)), false, 'stale file beside user content survived regeneration');
    assert.strictEqual(fs.readFileSync(userSibling, 'utf8'), 'must survive cleanup\n', 'cleanup modified an unowned sibling');
    assert.deepStrictEqual(isolatedCompiler.compileAdapters({ check: true }).changed, []);

    const goodInventory = fs.readFileSync(inventoryPath);
    const protectedPrompt = path.join(clioRoot, 'prompts', 'wtfp', 'help.md');
    fs.writeFileSync(protectedPrompt, 'locally corrupted output\n');
    const malformed = JSON.parse(goodInventory.toString('utf8'));
    malformed.target = 'not-clio';
    fs.writeFileSync(inventoryPath, `${JSON.stringify(malformed, null, 2)}\n`);
    assert.throws(
      () => isolatedCompiler.compileAdapters(),
      /refusing malformed generated inventory for clio/,
      'a malformed ownership receipt did not fail closed'
    );
    assert.strictEqual(fs.readFileSync(protectedPrompt, 'utf8'), 'locally corrupted output\n', 'compiler wrote before validating ownership');

    fs.writeFileSync(inventoryPath, goodInventory);
    fs.writeFileSync(protectedPrompt, isolatedCompiler.compilePlans().find((plan) => plan.id === 'clio').files.get('prompts/wtfp/help.md'));
    const traversing = JSON.parse(goodInventory.toString('utf8'));
    traversing.files.push({ path: '../../escape', sha256: sha256('escape') });
    fs.writeFileSync(inventoryPath, `${JSON.stringify(traversing, null, 2)}\n`);
    assert.throws(
      () => isolatedCompiler.compileAdapters(),
      /prior generated path escapes its target/,
      'a traversing stale path was accepted'
    );
  } finally {
    fs.rmSync(temporaryRoot, { recursive: true, force: true });
  }
});

record('every command-capable host exposes the same 36 stable aliases', () => {
  assert.strictEqual(actionIds.length, 36);
  assert.strictEqual(new Set(actionIds).size, 36);
  assert.deepStrictEqual(aliases.map((entry) => entry.alias), actionIds.map((id) => `wtfp:${id}`));

  for (const target of ['clio', 'claude', 'copilot', 'opencode', 'antigravity', 'gemini']) {
    const plan = plansById.get(target);
    const expected = commandPaths(target, actionIds);
    const pattern = target === 'clio'
      ? /^prompts\/wtfp\/[^/]+\.md$/
      : target === 'claude'
        ? /^commands\/[^/]+\.md$/
      : target === 'gemini'
        ? /^commands\/wtfp\/[^/]+\.toml$/
        : target === 'copilot' || target === 'antigravity'
          ? /^commands\/wtfp-[^/]+\.md$/
        : /^commands\/wtfp\/[^/]+\.md$/;
    assert.deepStrictEqual(planFiles(plan, pattern), sorted(expected), `${target}: command alias surface drift`);
    assert.deepStrictEqual(JSON.parse(planText(plan, 'aliases.lock.json')), { schema: 'wtfp.aliases/v1', namespace: 'wtfp', aliases });

    for (const [index, sourcePath] of expected.entries()) {
      const source = planText(plan, sourcePath);
      assert.ok(source.includes(GENERATED_BANNER), `${target}:${sourcePath}: missing source banner`);
      assert.match(source, /^## Invocation input$/m, `${target}:${sourcePath}: invocation input is not forwarded`);
      assert.match(source, /^## Bound action contract and schemas$/m, `${target}:${sourcePath}: action contract binding is missing`);
      assert.ok(source.includes(`actions/${actionIds[index]}.json`), `${target}:${sourcePath}: exact action contract is not bound`);
      assert.ok(
        source.includes(target === 'gemini' ? '{{args}}' : '$ARGUMENTS'),
        `${target}:${sourcePath}: native argument placeholder is missing`
      );
      if (!['clio', 'claude', 'gemini'].includes(target)) {
        assert.match(source, new RegExp(`^name: wtfp:${actionIds[index]}$`, 'm'));
      }
      if (target === 'claude') assert.doesNotMatch(source, /^name:/m, `${sourcePath}: Claude command name must be path-derived`);
      if (actionIds[index] === 'new-paper') {
        for (const schema of ['common', 'config', 'decisions', 'manifest', 'outline', 'state']) {
          assert.ok(source.includes(`project/schemas/${schema}.schema.json`), `${target}:${sourcePath}: missing ${schema} schema`);
          if (schema !== 'common') {
            assert.ok(source.includes(`project/templates/${schema}.json`), `${target}:${sourcePath}: missing ${schema} template`);
          }
        }
      }
    }
  }
});

record('all seven envelopes contain exactly the seven canonical Agent Skills', () => {
  for (const target of Object.keys(EXPECTED_ROOTS)) {
    const plan = plansById.get(target);
    const skillFiles = planFiles(plan, /^skills\/[^/]+\/SKILL\.md$/);
    assert.deepStrictEqual(
      skillFiles,
      EXPECTED_SKILLS.map((skill) => `skills/${skill}/SKILL.md`),
      `${target}: skill catalog drift`
    );
    assertSkillLinksResolve(plan);
  }
});

record('all seven envelopes expose only declared tools at URI-derived module paths', () => {
  const expected = toolsRegistry
    .map((tool) => `tools/${tool.implementation.slice('wtfp://tools/'.length)}.js`)
    .sort((left, right) => left.localeCompare(right));
  for (const target of Object.keys(EXPECTED_ROOTS)) {
    const plan = plansById.get(target);
    assert.deepStrictEqual(planFiles(plan, /^tools\/.*\.js$/), expected, `${target}: bundled tool surface drift`);
    assert.ok(plan.files.has('tools/README.md'), `${target}: logical tool resolver documentation is missing`);
    for (const sourcePath of expected) {
      const source = planText(plan, sourcePath);
      for (const match of source.matchAll(/require\((?:'|")(\.\.?\/[^'"]+)(?:'|")\)/g)) {
        const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(sourcePath), match[1]));
        assert.ok(plan.files.has(resolved), `${target}:${sourcePath}: undeclared module dependency ${match[1]}`);
      }
    }
    for (const forbidden of ['adapter-compiler.js', 'checkpoint.js', 'context-primer.js', 'manifest.js', 'native-registration.js', 'ownership.js', 'utils.js', 'wcn-compiler.js']) {
      assert.ok(![...plan.files.keys()].some((file) => file === `tools/${forbidden}` || file.endsWith(`/${forbidden}`)), `${target}: unsafe internal tool leaked: ${forbidden}`);
    }
  }
});

record('supported hosts contain exactly 11 generated native roles', () => {
  for (const target of ['clio', 'claude', 'copilot', 'opencode', 'antigravity', 'gemini']) {
    const plan = plansById.get(target);
    const expected = expectedAgentPaths(target);
    const actual = ['clio', 'copilot', 'antigravity'].includes(target)
      ? planFiles(plan, /^agents\/wtfp-[^/]+\.md$/)
      : planFiles(plan, /^agents\/wtfp\/[^/]+\.md$/);
    assert.deepStrictEqual(actual, expected, `${target}: native role surface drift`);
    for (const sourcePath of expected) {
      assert.ok(planText(plan, sourcePath).includes(GENERATED_BANNER), `${target}:${sourcePath}: missing source banner`);
    }
  }
  assert.deepStrictEqual(planFiles(plansById.get('codex'), /^agents\//), [], 'Codex should expose roles through skills, not an invented agent format');
});

record('Clio emits nested and flat prompts, strict agents, and two agent-only fleets', () => {
  const plan = plansById.get('clio');
  const nested = actionIds.map((id) => `prompts/wtfp/${id}.md`);
  const flat = actionIds.map((id) => `prompts/wtfp-${id}.md`);
  assert.deepStrictEqual(planFiles(plan, /^prompts\/wtfp\/[^/]+\.md$/), sorted(nested));
  assert.deepStrictEqual(planFiles(plan, /^prompts\/wtfp-[^/]+\.md$/), sorted(flat));
  for (const [index, nestedPath] of nested.entries()) {
    assert.deepStrictEqual(plan.files.get(nestedPath), plan.files.get(flat[index]), `${actionIds[index]}: Clio compatibility prompt drift`);
  }

  assert.ok([...plan.files.keys()].every((file) => !file.split('/').some((segment) => segment.includes(':'))), 'Clio generated a colon-bearing filename');
  for (const role of EXPECTED_ROLES) {
    const sourcePath = `agents/wtfp-${role}.md`;
    const source = planText(plan, sourcePath);
    const verifier = ['argument-verifier', 'coherence-checker', 'plan-checker', 'section-reviewer'].includes(role);
    assert.match(source, /^---\nversion: 1\n/);
    assert.ok(source.includes(`\nskills: [${CLIO_ROLE_SKILLS[role]}]\n`), `${sourcePath}: incorrect skill binding`);
    assert.match(source, /^audience: custom$/m);
    assert.match(source, /^projectContextTier: bounded$/m);
    assert.match(source, /^budget: \{toolCalls: \d+, readReserve: \d+, synthesis: true\}$/m);
    assert.match(source, new RegExp(`^resultContract: \\{kind: ${verifier ? 'verifier-report' : 'mutation-report'}\\}$`, 'm'));
    assert.match(source, /^## Clio result contract$/m);
    assert.match(source, /entire final response must be one JSON object/);
  }

  const fleetPaths = planFiles(plan, /^fleets\/[^/]+\.md$/);
  assert.deepStrictEqual(fleetPaths, ['fleets/wtfp-draft-review.md', 'fleets/wtfp-plan-section.md']);
  const expectedFleetAgents = {
    'fleets/wtfp-draft-review.md': ['wtfp-section-writer', 'wtfp-section-reviewer'],
    'fleets/wtfp-plan-section.md': ['wtfp-section-planner', 'wtfp-plan-checker']
  };
  for (const sourcePath of fleetPaths) {
    const source = planText(plan, sourcePath);
    assert.match(source, /^---\nversion: 4\n/);
    assert.ok(source.includes(GENERATED_BANNER), `${sourcePath}: missing source banner`);
    assert.doesNotMatch(source, /^\s*- kind: code$/m, `${sourcePath}: initial Clio fleets must remain agent-only`);
    const agents = [...source.matchAll(/^\s+agent: (wtfp-[a-z0-9-]+)$/gm)].map((match) => match[1]);
    assert.deepStrictEqual(agents, expectedFleetAgents[sourcePath]);
    for (const agent of agents) assert.ok(plan.files.has(`agents/${agent}.md`), `${sourcePath}: missing bound agent ${agent}`);
  }
});

record('Copilot carries a committed cloud-safe repository projection', () => {
  const plan = plansById.get('copilot-marketplace');
  const prompts = planFiles(plan, /^project\/\.github\/prompts\/wtfp-[^/]+\.prompt\.md$/);
  const agents = planFiles(plan, /^project\/\.github\/agents\/wtfp-[^/]+\.agent\.md$/);
  const skills = planFiles(plan, /^project\/\.github\/skills\/[^/]+\/SKILL\.md$/);
  assert.strictEqual(prompts.length, 36);
  assert.strictEqual(agents.length, 11);
  assert.deepStrictEqual(
    skills,
    EXPECTED_SKILLS.map((skill) => `project/.github/skills/${skill}/SKILL.md`)
  );
  assert.ok(plan.files.has('project/.github/copilot-instructions.md'));
  assert.ok(plan.files.has('project/.github/wtfp/project/README.md'));
  for (const sourcePath of [...prompts, ...agents]) {
    const source = planText(plan, sourcePath);
    assert.ok(source.includes(GENERATED_BANNER), `${sourcePath}: missing provenance`);
    assert.doesNotMatch(source, /\$\{CLAUDE_PLUGIN_ROOT\}/, `${sourcePath}: user-plugin root leaked into cloud projection`);
    assert.doesNotMatch(source, /\$ARGUMENTS/, `${sourcePath}: local-plugin arguments leaked into cloud projection`);
    assert.doesNotMatch(source, /^@\.github\//m, `${sourcePath}: local-plugin include leaked into cloud projection`);
    for (const match of source.matchAll(/\]\(\.\.\/wtfp\/([^)]+)\)/g)) {
      assert.ok(plan.files.has(`project/.github/wtfp/${match[1]}`), `${sourcePath}: unresolved cloud link ${match[0]}`);
    }
  }
  for (const sourcePath of prompts) {
    const source = planText(plan, sourcePath);
    assert.match(
      source,
      /\$\{input:arguments:Describe the requested WTF-P action input\}/,
      `${sourcePath}: missing Copilot input variable`
    );
    assert.match(source, /^tools: \[[^\n]+\]$/m, `${sourcePath}: missing bounded Copilot tools`);
  }
});

record('Codex, Claude, Copilot, Antigravity, Gemini, and Clio manifests resolve locally', () => {
  const codex = plansById.get('codex');
  const codexManifest = JSON.parse(planText(codex, '.codex-plugin/plugin.json'));
  assert.strictEqual(codexManifest.name, 'wtf-p');
  assert.strictEqual(codexManifest.version, PACKAGE_VERSION);
  assert.ok(codexManifest.description);
  assert.strictEqual(codexManifest.skills, './skills/');
  assert.ok(codexManifest.interface && codexManifest.interface.displayName === 'WTF-P');
  assertManifestDirectory(codex, codexManifest.skills, 'Codex skills');

  for (const target of ['claude', 'copilot']) {
    const plan = plansById.get(target);
    const manifest = JSON.parse(planText(plan, '.claude-plugin/plugin.json'));
    assert.strictEqual(manifest.name, target === 'claude' ? 'wtfp' : 'wtf-p');
    assert.strictEqual(manifest.version, PACKAGE_VERSION);
    assert.ok(manifest.description, `${target}: plugin manifest needs a description`);
    for (const resource of ['commands', 'agents', 'skills']) assertDirectory(plan, resource, `${target} ${resource}`);
  }

  const claudeMarketplace = JSON.parse(planText(plansById.get('claude'), '.claude-plugin/marketplace.json'));
  assert.strictEqual(claudeMarketplace.name, 'wtfp');
  assert.strictEqual(claudeMarketplace.plugins[0].name, 'wtfp');
  assert.strictEqual(claudeMarketplace.plugins[0].source, './');

  const antigravity = plansById.get('antigravity');
  const antigravityManifest = JSON.parse(planText(antigravity, 'plugin.json'));
  assert.strictEqual(antigravityManifest.version, PACKAGE_VERSION);
  for (const key of ['commands', 'agents', 'skills']) assertManifestDirectory(antigravity, antigravityManifest[key], `Antigravity ${key}`);

  const gemini = plansById.get('gemini');
  const geminiManifest = JSON.parse(planText(gemini, 'gemini-extension.json'));
  assert.strictEqual(geminiManifest.version, PACKAGE_VERSION);
  assert.ok(gemini.files.has(geminiManifest.contextFileName), 'Gemini contextFileName does not resolve');

  const clioManifest = planText(plansById.get('clio'), 'clio-coder-extension.yaml');
  assert.match(clioManifest, /^manifestVersion: 1$/m);
  assert.match(clioManifest, new RegExp(`^version: ${PACKAGE_VERSION.replace(/\./g, '\\.')}$$`, 'm'));
  for (const resource of ['skills', 'prompts', 'agents', 'fleets']) {
    assert.match(clioManifest, new RegExp(`^  ${resource}: ${resource}$`, 'm'));
    assertDirectory(plansById.get('clio'), resource, `Clio ${resource}`);
  }

  const codexMarketplace = JSON.parse(planText(
    plansById.get('codex-marketplace'),
    '.agents/plugins/marketplace.json'
  ));
  assert.deepStrictEqual(codexMarketplace.plugins[0].source, { source: 'local', path: './plugins/wtf-p' });
  assert.ok(plansById.get('codex').root.startsWith(`${plansById.get('codex-marketplace').root}${path.sep}`));

  const copilotMarketplace = JSON.parse(planText(plansById.get('copilot-marketplace'), 'marketplace.json'));
  assert.strictEqual(copilotMarketplace.plugins[0].source, './plugins/wtf-p');
  assert.ok(plansById.get('copilot').root.startsWith(`${plansById.get('copilot-marketplace').root}${path.sep}`));
});

record('every bundled native resource reference resolves inside its target envelope', () => {
  for (const target of ['clio', 'claude', 'copilot', 'opencode', 'antigravity', 'gemini']) {
    const plan = plansById.get(target);
    const nativePaths = [
      ...commandPaths(target, actionIds),
      ...expectedAgentPaths(target)
    ];
    assertSelfContained(plan, nativePaths, ['clio', 'claude', 'copilot', 'antigravity'].includes(target));
    if (target === 'gemini') {
      for (const sourcePath of nativePaths) {
        assert.doesNotMatch(planText(plan, sourcePath), /\$\{extensionPath\}/, `${sourcePath}: unsupported Gemini prompt variable`);
      }
    }
  }
});

if (failures.length > 0) {
  process.stderr.write(`\n${failures.length} adapter compiler contract(s) failed; ${passed} passed.\n`);
  process.exitCode = 1;
} else {
  process.stdout.write(`\n${passed} adapter compiler contracts passed.\n`);
}
