#!/usr/bin/env node

'use strict';

const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const {
  GENERATOR_VERSION,
  TARGET_POLICIES,
  TARGET_ROOTS,
  compilePlans,
  inventoryFor
} = require('../bin/lib/adapter-compiler');

const ROOT = path.resolve(__dirname, '..');
const BUILD = path.join(ROOT, 'scripts', 'build-adapters.js');
const PACKAGE_VERSION = require('../package.json').version;
const GENERATED_BANNER = `Generated by WTF-P adapter compiler v${GENERATOR_VERSION}`;

const EXPECTED_ROOTS = Object.freeze({
  antigravity: path.join(ROOT, 'vendors', 'antigravity'),
  claude: path.join(ROOT, 'vendors', 'claude'),
  codex: path.join(ROOT, 'vendors', 'codex', 'plugins', 'wtf-p'),
  copilot: path.join(ROOT, 'vendors', 'copilot', 'plugins', 'wtf-p'),
  gemini: path.join(ROOT, 'vendors', 'gemini'),
  opencode: path.join(ROOT, 'vendors', 'opencode')
});

const EXPECTED_SKILLS = [
  'wtfp-deliver-research',
  'wtfp-manage-project',
  'wtfp-plan-section',
  'wtfp-research-literature',
  'wtfp-review-manuscript',
  'wtfp-start-project',
  'wtfp-write-section'
];

const EXPECTED_ROLES = [
  'argument-verifier',
  'citation-expert',
  'citation-formatter',
  'coherence-checker',
  'outliner',
  'plan-checker',
  'prose-polisher',
  'research-synthesizer',
  'section-planner',
  'section-reviewer',
  'section-writer'
];

const CLIO_ROLE_SKILLS = Object.freeze({
  'argument-verifier': 'wtfp-review-manuscript',
  'citation-expert': 'wtfp-research-literature',
  'citation-formatter': 'wtfp-research-literature',
  'coherence-checker': 'wtfp-review-manuscript',
  'outliner': 'wtfp-start-project',
  'plan-checker': 'wtfp-plan-section',
  'prose-polisher': 'wtfp-review-manuscript',
  'research-synthesizer': 'wtfp-research-literature',
  'section-planner': 'wtfp-plan-section',
  'section-reviewer': 'wtfp-review-manuscript',
  'section-writer': 'wtfp-write-section'
});

// Blocked everywhere: no target binds external issue creation, file deletion,
// or package self-update.
const BLOCKED_ACTIONS = Object.freeze([
  'contribute',
  'remove-section',
  'report-bug',
  'request-feature',
  'update'
]);

// Blocked wherever `tool.execute` is unbound, which is every host whose shell
// tool name is not verified by the adapter policy.
const BUNDLED_TOOL_ACTIONS = Object.freeze([
  'analyze-bib',
  'audit-milestone',
  'check-refs',
  'export-latex',
  'research-gap'
]);

const BUNDLED_TOOL_TARGETS = Object.freeze(['claude', 'clio']);

const GATED_NETWORK_ACTIONS = Object.freeze([
  'analyze-bib',
  'check-refs',
  'contribute',
  'report-bug',
  'request-feature',
  'research-gap',
  'update'
]);

const failures = [];
let passed = 0;

function record(name, test) {
  try {
    test();
    passed++;
    process.stdout.write(`\x1b[32m✓\x1b[0m ${name}\n`);
  } catch (error) {
    failures.push({ name, error });
    process.stderr.write(`\x1b[31m✗\x1b[0m ${name}\n${error.stack || error.message}\n`);
  }
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function sha256(content) {
  return crypto.createHash('sha256').update(content).digest('hex');
}

function posix(value) {
  return value.split(path.sep).join('/');
}

function sorted(values) {
  return [...values].sort((left, right) => left.localeCompare(right));
}

function planFiles(plan, pattern) {
  return sorted([...plan.files.keys()].filter((file) => pattern.test(file)));
}

function planText(plan, relativePath) {
  const content = plan.files.get(relativePath);
  assert.ok(content, `${plan.id}: missing generated file ${relativePath}`);
  return content.toString('utf8');
}

function assertDirectory(plan, relativePath, context) {
  const prefix = `${relativePath.replace(/\/$/, '')}/`;
  assert.ok(
    [...plan.files.keys()].some((file) => file.startsWith(prefix)),
    `${plan.id}: ${context} points at missing directory ${relativePath}`
  );
}

function assertManifestDirectory(plan, reference, context) {
  assert.match(reference, /^\.\/[a-z][a-z0-9-]*\/?$/, `${plan.id}: unsafe ${context} path ${reference}`);
  assertDirectory(plan, reference.replace(/^\.\//, ''), context);
}

function commandPaths(target, actionIds) {
  if (target === 'clio') return actionIds.map((id) => `prompts/wtfp/${id}.md`);
  if (target === 'claude') return actionIds.map((id) => `commands/${id}.md`);
  if (target === 'gemini') return actionIds.map((id) => `commands/wtfp/${id}.toml`);
  if (target === 'copilot' || target === 'antigravity') {
    return actionIds.map((id) => `commands/wtfp-${id}.md`);
  }
  return actionIds.map((id) => `commands/wtfp/${id}.md`);
}

// Every host except OpenCode reads only the top level of `agents/`. OpenCode
// scans recursively and registers the frontmatter name, so its namespace
// directory is kept.
const FLAT_AGENT_TARGETS = Object.freeze(['clio', 'claude', 'copilot', 'antigravity', 'gemini']);

function expectedAgentPaths(target) {
  if (FLAT_AGENT_TARGETS.includes(target)) {
    return EXPECTED_ROLES.map((role) => `agents/wtfp-${role}.md`);
  }
  return EXPECTED_ROLES.map((role) => `agents/wtfp/${role}.md`);
}

function planFingerprint(plans) {
  return plans.map((plan) => ({
    id: plan.id,
    root: plan.root,
    inventory: inventoryFor(plan)
  }));
}

function snapshotInventories(plans) {
  return new Map(plans.filter((plan) => plan.root).map((plan) => {
    const inventoryPath = path.join(plan.root, '.wtfp-generated.json');
    return [inventoryPath, fs.readFileSync(inventoryPath)];
  }));
}

function isolatedEnvironment(root) {
  const home = path.join(root, 'home');
  return {
    ...process.env,
    HOME: home,
    USERPROFILE: home,
    XDG_CONFIG_HOME: path.join(root, 'xdg', 'config'),
    XDG_DATA_HOME: path.join(root, 'xdg', 'data'),
    XDG_STATE_HOME: path.join(root, 'xdg', 'state'),
    XDG_CACHE_HOME: path.join(root, 'xdg', 'cache'),
    CLAUDE_CONFIG_DIR: path.join(root, 'clients', 'claude'),
    CLIO_CODER_CONFIG_DIR: path.join(root, 'clients', 'clio'),
    CODEX_HOME: path.join(root, 'clients', 'codex'),
    COPILOT_HOME: path.join(root, 'clients', 'copilot'),
    GEMINI_CLI_HOME: path.join(root, 'clients', 'gemini'),
    OPENCODE_CONFIG_DIR: path.join(root, 'clients', 'opencode'),
    ANTIGRAVITY_HOME: path.join(root, 'clients', 'antigravity'),
    FORCE_COLOR: '',
    NO_COLOR: '1'
  };
}

function runCheck(cwd, environment) {
  return spawnSync(process.execPath, [BUILD, '--check'], {
    cwd,
    env: environment,
    encoding: 'utf8',
    input: '',
    timeout: 30000
  });
}

function copyCompilerFixture(destination) {
  const copies = [
    ['bin/lib', 'bin/lib'],
    ['protocol', 'protocol']
  ];
  for (const [source, target] of copies) {
    fs.cpSync(path.join(ROOT, source), path.join(destination, target), { recursive: true });
  }
  for (const file of ['CONTRIBUTING.md', 'package.json']) {
    fs.mkdirSync(path.dirname(path.join(destination, file)), { recursive: true });
    fs.copyFileSync(path.join(ROOT, file), path.join(destination, file));
  }
}

function assertCheckSuccess(result, context) {
  assert.ifError(result.error);
  assert.strictEqual(result.signal, null, `${context}: terminated by ${result.signal}`);
  assert.strictEqual(result.status, 0, `${context}\n${result.stdout || ''}${result.stderr || ''}`);
  assert.strictEqual(result.stderr, '', `${context}: wrote unexpected stderr`);
  assert.match(result.stdout, /^Generated adapters are current \(\d+ envelopes\)\.\n$/);
}

function staticReferenceCandidates(reference) {
  const candidates = [reference];
  if (/[.,;:!?]$/.test(reference)) candidates.push(reference.slice(0, -1));
  return candidates;
}

function assertBundleReference(plan, reference, sourcePath) {
  for (const candidate of staticReferenceCandidates(reference)) {
    assert.ok(!path.posix.isAbsolute(candidate), `${plan.id}:${sourcePath}: absolute bundle reference ${candidate}`);
    assert.ok(!candidate.split('/').includes('..'), `${plan.id}:${sourcePath}: traversing bundle reference ${candidate}`);

    const dynamicAt = candidate.search(/[{}*]/);
    if (dynamicAt !== -1) {
      const staticPrefix = candidate.slice(0, dynamicAt);
      if ([...plan.files.keys()].some((file) => file.startsWith(staticPrefix))) return;
      continue;
    }
    if (plan.files.has(candidate)) return;
    if ([...plan.files.keys()].some((file) => file.startsWith(`${candidate.replace(/\/$/, '')}/`))) return;
  }
  assert.fail(`${plan.id}:${sourcePath}: bundle reference does not resolve inside its envelope: ${reference}`);
}

function assertSelfContained(plan, nativePaths, transformProtocolReferences) {
  let references = 0;
  for (const sourcePath of nativePaths) {
    const source = planText(plan, sourcePath);
    const logical = /protocol:\/\/([A-Za-z0-9._{}*/-]+)/g;
    const rooted = /\$\{(?:pluginRoot|extensionRoot|extensionPath|CLAUDE_PLUGIN_ROOT|PLUGIN_ROOT)\}\/([A-Za-z0-9._{}*/-]+)/g;
    for (const pattern of [logical, rooted]) {
      for (const match of source.matchAll(pattern)) {
        references++;
        assertBundleReference(plan, match[1], sourcePath);
      }
    }
    assert.doesNotMatch(source, /^@protocol:\/\//m, `${plan.id}:${sourcePath}: unresolved protocol include`);
    if (transformProtocolReferences) {
      assert.doesNotMatch(
        source,
        /protocol:\/\//,
        `${plan.id}:${sourcePath}: a native bundle reference was not rewritten`
      );
    }
  }
  assert.ok(references > 0, `${plan.id}: no bundle references were checked`);
}

function assertSkillLinksResolve(plan) {
  for (const sourcePath of planFiles(plan, /^skills\/[^/]+\/.*\.md$/)) {
    const source = planText(plan, sourcePath);
    for (const match of source.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) {
      const reference = match[1].split('#')[0];
      if (!reference || /^[a-z][a-z0-9+.-]*:/i.test(reference) || reference.startsWith('/')) continue;
      const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(sourcePath), reference));
      assert.ok(!resolved.startsWith('../'), `${plan.id}:${sourcePath}: link escapes the bundle: ${reference}`);
      assert.ok(plan.files.has(resolved), `${plan.id}:${sourcePath}: broken bundled link ${reference}`);
    }
  }
}

const firstPlans = compilePlans();
const plansById = new Map(firstPlans.map((plan) => [plan.id, plan]));
const aliases = readJson(path.join(ROOT, 'protocol', 'aliases.lock.json')).aliases;
const actionIds = aliases.map((entry) => entry.action);
const toolsRegistry = readJson(path.join(ROOT, 'protocol', 'tools.json')).tools;

function expectedBlockedActions(target) {
  const base = BUNDLED_TOOL_TARGETS.includes(target)
    ? [...BLOCKED_ACTIONS]
    : sorted([...BLOCKED_ACTIONS, ...BUNDLED_TOOL_ACTIONS]);
  if (target !== 'copilot-cloud') return base;
  const explicitEffects = new Set(readJson(path.join(ROOT, 'protocol', 'effects.json')).effects
    .filter((effect) => effect.consent === 'explicit')
    .map((effect) => effect.id));
  return actionIds.filter((actionId) => {
    const action = readJson(path.join(ROOT, 'protocol', 'actions', `${actionId}.json`));
    return base.includes(actionId) || action.effects.some((effect) => explicitEffects.has(effect.id));
  });
}

record('compiler plans and target roots are exact and deterministic', () => {
  assert.deepStrictEqual(TARGET_ROOTS, EXPECTED_ROOTS);
  assert.deepStrictEqual(
    firstPlans.map((plan) => [plan.id, plan.root]),
    [
      ['claude', EXPECTED_ROOTS.claude],
      ['codex', EXPECTED_ROOTS.codex],
      ['copilot', EXPECTED_ROOTS.copilot],
      ['opencode', EXPECTED_ROOTS.opencode],
      ['antigravity', EXPECTED_ROOTS.antigravity],
      ['gemini', EXPECTED_ROOTS.gemini],
      ['portable-plugin', path.join(ROOT, 'vendors', 'plugin')],
      ['codex-marketplace', path.join(ROOT, 'vendors', 'codex')],
      ['copilot-marketplace', path.join(ROOT, 'vendors', 'copilot')],
      ['clio', null]
    ]
  );
  assert.deepStrictEqual(planFingerprint(compilePlans()), planFingerprint(firstPlans));
});

record('target capability and approval policies are exhaustive and fail closed', () => {
  const targets = ['antigravity', 'claude', 'clio', 'codex', 'copilot', 'copilot-cloud', 'gemini', 'opencode'];
  assert.deepStrictEqual(sorted(Object.keys(TARGET_POLICIES)), targets);
  const clone = () => JSON.parse(JSON.stringify(TARGET_POLICIES));

  const missingTarget = clone();
  delete missingTarget.clio;
  assert.throws(() => compilePlans({ targetPolicies: missingTarget }), /target capability policies must map exactly/);

  const unknownTarget = clone();
  unknownTarget.future = unknownTarget.clio;
  assert.throws(() => compilePlans({ targetPolicies: unknownTarget }), /target capability policies must map exactly/);

  const missingCapability = clone();
  delete missingCapability.codex.capabilities['filesystem.read'];
  assert.throws(() => compilePlans({ targetPolicies: missingCapability }), /target capability policy codex must map exactly/);

  const malformedBinding = clone();
  malformedBinding.claude.capabilities['filesystem.read'] = 'Read';
  assert.throws(() => compilePlans({ targetPolicies: malformedBinding }), /malformed exact binding for filesystem\.read/);

  const malformedApproval = clone();
  malformedApproval['copilot-cloud'].approvals.explicit = 'input-approval';
  assert.throws(() => compilePlans({ targetPolicies: malformedApproval }), /malformed exact approval binding for explicit/);

  assert.strictEqual(TARGET_POLICIES.clio.capabilities['user.interaction'], 'clio:ask_user');
  assert.strictEqual(TARGET_POLICIES.clio.approvals.explicit, 'clio:ask_user');
  assert.doesNotThrow(() => compilePlans(), 'native tool bindings may contain underscores after the target prefix');

  const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'wtfp-policy-registry-'));
  try {
    copyCompilerFixture(temporaryRoot);
    const registryPath = path.join(temporaryRoot, 'protocol', 'effects.json');
    const registry = readJson(registryPath);
    registry.effects.push({
      id: 'future.effect',
      consent: 'explicit',
      reversibility: 'not-applicable',
      description: 'Unmapped test effect.'
    });
    fs.writeFileSync(registryPath, `${JSON.stringify(registry, null, 2)}\n`);
    const isolatedCompiler = require(path.join(temporaryRoot, 'bin', 'lib', 'adapter-compiler.js'));
    assert.throws(() => isolatedCompiler.compilePlans(), /effect capability bindings must map exactly/);
  } finally {
    fs.rmSync(temporaryRoot, { recursive: true, force: true });
  }
});

record('generated inventories exactly authenticate every compiler-owned file', () => {
  for (const plan of firstPlans.filter((candidate) => candidate.root)) {
    const inventoryPath = path.join(plan.root, '.wtfp-generated.json');
    const inventory = readJson(inventoryPath);
    assert.deepStrictEqual(inventory, inventoryFor(plan), `${plan.id}: stale or nondeterministic inventory`);
    assert.strictEqual(inventory.schema, 'wtfp.generated-adapter/v1');
    assert.strictEqual(inventory.target, plan.id);
    assert.deepStrictEqual(inventory.files.map((file) => file.path), sorted(plan.files.keys()));
    for (const file of inventory.files) {
      assert.match(file.sha256, /^[a-f0-9]{64}$/);
      assert.ok(!path.posix.isAbsolute(file.path), `${plan.id}: inventory contains an absolute path`);
      assert.ok(!file.path.split('/').includes('..'), `${plan.id}: inventory path traverses its root`);
      const actual = fs.readFileSync(path.join(plan.root, file.path));
      assert.strictEqual(sha256(actual), file.sha256, `${plan.id}: generated file hash drift: ${file.path}`);
    }
  }
});

record('real --check is read-only and emits identical results from an isolated home', () => {
  const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'wtfp-adapter-check-'));
  try {
    const before = snapshotInventories(firstPlans);
    const environment = isolatedEnvironment(temporaryRoot);
    const first = runCheck(temporaryRoot, environment);
    const second = runCheck(temporaryRoot, environment);
    assertCheckSuccess(first, 'first adapter --check');
    assertCheckSuccess(second, 'second adapter --check');
    assert.strictEqual(second.stdout, first.stdout, '--check output is not deterministic');
    assert.strictEqual(second.stderr, first.stderr, '--check diagnostics are not deterministic');
    for (const [inventoryPath, content] of before) {
      assert.deepStrictEqual(fs.readFileSync(inventoryPath), content, `--check mutated ${inventoryPath}`);
    }
    assert.deepStrictEqual(
      fs.readdirSync(temporaryRoot).sort(),
      [],
      '--check created state in its isolated working directory or home'
    );
  } finally {
    fs.rmSync(temporaryRoot, { recursive: true, force: true });
  }
});

record('stale inventory cleanup is exact, read-only in check mode, and fail-closed', () => {
  const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'wtfp-adapter-stale-'));
  try {
    copyCompilerFixture(temporaryRoot);
    const isolatedCompilerPath = path.join(temporaryRoot, 'bin', 'lib', 'adapter-compiler.js');
    const isolatedCompiler = require(isolatedCompilerPath);
    isolatedCompiler.compileAdapters();

    const clioRoot = path.join(temporaryRoot, 'vendors', 'plugin');
    const inventoryPath = path.join(clioRoot, '.wtfp-generated.json');
    const staleEmpty = 'retired/empty/compiler-owned.md';
    const staleShared = 'retired/shared/compiler-owned.md';
    const userSibling = path.join(clioRoot, 'retired', 'shared', 'user-owned.md');
    for (const relativePath of [staleEmpty, staleShared]) {
      const absolutePath = path.join(clioRoot, relativePath);
      fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
      fs.writeFileSync(absolutePath, 'stale compiler output\n');
    }
    fs.writeFileSync(userSibling, 'must survive cleanup\n');

    const priorInventory = readJson(inventoryPath);
    priorInventory.files.push(
      { path: staleEmpty, sha256: sha256('stale compiler output\n') },
      { path: staleShared, sha256: sha256('stale compiler output\n') }
    );
    priorInventory.files.sort((left, right) => left.path.localeCompare(right.path));
    fs.writeFileSync(inventoryPath, `${JSON.stringify(priorInventory, null, 2)}\n`);
    const inventoryBeforeCheck = fs.readFileSync(inventoryPath);

    assert.throws(
      () => isolatedCompiler.compileAdapters({ check: true }),
      (error) => /generated adapters are stale/.test(error.message)
        && error.message.includes(`stale:${staleEmpty}`)
        && error.message.includes(`stale:${staleShared}`),
      'check mode did not report both stale owned paths'
    );
    assert.deepStrictEqual(fs.readFileSync(inventoryPath), inventoryBeforeCheck, 'check mode rewrote the prior inventory');
    assert.ok(fs.existsSync(path.join(clioRoot, staleEmpty)), 'check mode removed a stale file');
    assert.ok(fs.existsSync(path.join(clioRoot, staleShared)), 'check mode removed a stale shared file');

    const result = isolatedCompiler.compileAdapters();
    const clioChanges = result.changed.find((entry) => entry.target === 'portable-plugin');
    assert.ok(clioChanges, 'build omitted the changed canonical plugin target');
    assert.ok(clioChanges.files.includes(`stale:${staleEmpty}`));
    assert.ok(clioChanges.files.includes(`stale:${staleShared}`));
    assert.strictEqual(fs.existsSync(path.join(clioRoot, staleEmpty)), false, 'stale owned file survived regeneration');
    assert.strictEqual(fs.existsSync(path.join(clioRoot, 'retired', 'empty')), false, 'empty stale directory survived regeneration');
    assert.strictEqual(fs.existsSync(path.join(clioRoot, staleShared)), false, 'stale file beside user content survived regeneration');
    assert.strictEqual(fs.readFileSync(userSibling, 'utf8'), 'must survive cleanup\n', 'cleanup modified an unowned sibling');
    assert.deepStrictEqual(isolatedCompiler.compileAdapters({ check: true }).changed, []);

    const goodInventory = fs.readFileSync(inventoryPath);
    const protectedPrompt = path.join(clioRoot, 'ai.iowarp.clio', 'prompts', 'wtfp', 'help.md');
    fs.writeFileSync(protectedPrompt, 'locally corrupted output\n');
    const malformed = JSON.parse(goodInventory.toString('utf8'));
    malformed.target = 'not-the-plugin';
    fs.writeFileSync(inventoryPath, `${JSON.stringify(malformed, null, 2)}\n`);
    assert.throws(
      () => isolatedCompiler.compileAdapters(),
      /refusing malformed generated inventory for portable-plugin/,
      'a malformed ownership receipt did not fail closed'
    );
    assert.strictEqual(fs.readFileSync(protectedPrompt, 'utf8'), 'locally corrupted output\n', 'compiler wrote before validating ownership');

    fs.writeFileSync(inventoryPath, goodInventory);
    fs.writeFileSync(protectedPrompt, isolatedCompiler.compilePlans().find((plan) => plan.id === 'portable-plugin').files.get('ai.iowarp.clio/prompts/wtfp/help.md'));
    const traversing = JSON.parse(goodInventory.toString('utf8'));
    traversing.files.push({ path: '../../escape', sha256: sha256('escape') });
    fs.writeFileSync(inventoryPath, `${JSON.stringify(traversing, null, 2)}\n`);
    assert.throws(
      () => isolatedCompiler.compileAdapters(),
      /prior generated path escapes its target/,
      'a traversing stale path was accepted'
    );
  } finally {
    fs.rmSync(temporaryRoot, { recursive: true, force: true });
  }
});

record('every command-capable host exposes the same stable aliases', () => {
  assert.strictEqual(new Set(actionIds).size, actionIds.length);
  assert.deepStrictEqual(aliases.map((entry) => entry.alias), actionIds.map((id) => `wtfp:${id}`));

  for (const target of ['clio', 'claude', 'copilot', 'opencode', 'antigravity', 'gemini']) {
    const plan = plansById.get(target);
    const expected = commandPaths(target, actionIds);
    const pattern = target === 'clio'
      ? /^prompts\/wtfp\/[^/]+\.md$/
      : target === 'claude'
        ? /^commands\/[^/]+\.md$/
      : target === 'gemini'
        ? /^commands\/wtfp\/[^/]+\.toml$/
        : target === 'copilot' || target === 'antigravity'
          ? /^commands\/wtfp-[^/]+\.md$/
        : /^commands\/wtfp\/[^/]+\.md$/;
    assert.deepStrictEqual(planFiles(plan, pattern), sorted(expected), `${target}: command alias surface drift`);
    assert.deepStrictEqual(JSON.parse(planText(plan, 'aliases.lock.json')), { schema: 'wtfp.aliases/v1', namespace: 'wtfp', aliases });

    for (const [index, sourcePath] of expected.entries()) {
      const source = planText(plan, sourcePath);
      assert.ok(source.includes(GENERATED_BANNER), `${target}:${sourcePath}: missing source banner`);
      if (!['clio', 'claude', 'gemini'].includes(target)) {
        assert.match(source, new RegExp(`^name: wtfp:${actionIds[index]}$`, 'm'));
      }
      if (target === 'claude') assert.doesNotMatch(source, /^name:/m, `${sourcePath}: Claude command name must be path-derived`);
      if (expectedBlockedActions(target).includes(actionIds[index])) {
        assert.match(source, /^WTFP_ACTION_UNAVAILABLE$/m, `${target}:${sourcePath}: missing blocked marker`);
        assert.ok(source.includes(`Action: \`${actionIds[index]}\``));
        assert.ok(source.includes(`Target: \`${target}\``));
        assert.match(source, /^No workflow, tool, network request, package operation, external issue, VCS operation, or other effect ran\.$/m);
        assert.match(source, /^Safe alternative:/m);
        assert.doesNotMatch(source, /^## Invocation input$/m, `${target}:${sourcePath}: blocked action received invocation input`);
        assert.doesNotMatch(source, /^## Bound action contract and schemas$/m, `${target}:${sourcePath}: blocked action received includes`);
        assert.doesNotMatch(source, /(?:\$ARGUMENTS|\{\{args\}\})/, `${target}:${sourcePath}: blocked action received arguments`);
        if (['claude', 'copilot', 'antigravity'].includes(target)) {
          assert.match(source, /^allowed-tools: \[\]$/m, `${target}:${sourcePath}: blocked action did not explicitly deny tools`);
          assert.doesNotMatch(source, /^allowed-tools:(?! \[\]$).+/m, `${target}:${sourcePath}: blocked action received tools`);
        } else {
          assert.doesNotMatch(source, /^(?:allowed-)?tools:/m, `${target}:${sourcePath}: blocked action received tools`);
        }
        continue;
      }
      assert.match(source, /^## Invocation input$/m, `${target}:${sourcePath}: invocation input is not forwarded`);
      assert.match(source, /^## Bound action contract and schemas$/m, `${target}:${sourcePath}: action contract binding is missing`);
      assert.ok(source.includes(`actions/${actionIds[index]}.json`), `${target}:${sourcePath}: exact action contract is not bound`);
      assert.ok(
        source.includes(target === 'gemini' ? '{{args}}' : '$ARGUMENTS'),
        `${target}:${sourcePath}: native argument placeholder is missing`
      );
      if (actionIds[index] === 'new-paper') {
        for (const schema of ['common', 'config', 'decisions', 'manifest', 'outline', 'state']) {
          assert.ok(source.includes(`project/schemas/${schema}.schema.json`), `${target}:${sourcePath}: missing ${schema} schema`);
          if (schema !== 'common') {
            assert.ok(source.includes(`project/templates/${schema}.json`), `${target}:${sourcePath}: missing ${schema} template`);
          }
        }
        assert.match(source, /outline\.sections\[\*\]\.word_target/,
          `${target}:${sourcePath}: exact outline word-budget field is not bound`);
        assert.match(source, /outline\.target_words/,
          `${target}:${sourcePath}: exact outline target field is not bound`);
        assert.doesNotMatch(source, /targetWords/,
          `${target}:${sourcePath}: non-schema targetWords spelling leaked into the contract`);
      }
      if (actionIds[index] === 'analyze-bib') {
        assert.ok(
          source.includes('project/schemas/section.schema.json'),
          `${target}:${sourcePath}: missing relevant section schema`
        );
        assert.ok(
          source.includes('project/templates/section.json'),
          `${target}:${sourcePath}: missing relevant section template`
        );
      }
    }
  }
});

record('all seven envelopes contain exactly the seven canonical Agent Skills', () => {
  for (const target of Object.keys(EXPECTED_ROOTS)) {
    const plan = plansById.get(target);
    const skillFiles = planFiles(plan, /^skills\/[^/]+\/SKILL\.md$/);
    assert.deepStrictEqual(
      skillFiles,
      EXPECTED_SKILLS.map((skill) => `skills/${skill}/SKILL.md`),
      `${target}: skill catalog drift`
    );
    assertSkillLinksResolve(plan);
  }
});

record('every target publishes exact action availability and skill-route blockers', () => {
  const projections = [
    ...Object.keys(EXPECTED_ROOTS).map((target) => ({
      target,
      plan: plansById.get(target),
      metadataPath: 'compatibility/action-availability.json',
      skillRoot: 'skills'
    })),
    {
      target: 'copilot-cloud',
      plan: plansById.get('copilot-marketplace'),
      metadataPath: 'project/.github/wtfp/compatibility/action-availability.json',
      skillRoot: 'project/.github/skills'
    }
  ];
  const catalog = readJson(path.join(ROOT, 'protocol', 'catalog.json'));

  for (const projection of projections) {
    const metadata = JSON.parse(planText(projection.plan, projection.metadataPath));
    assert.strictEqual(metadata.schema, 'wtfp.action-availability/v1');
    assert.strictEqual(metadata.target, projection.target);
    assert.strictEqual(metadata.marker, 'WTFP_ACTION_UNAVAILABLE');
    assert.deepStrictEqual(metadata.actions.map((action) => action.id), actionIds);
    assert.deepStrictEqual(
      metadata.actions.filter((action) => action.status === 'unavailable').map((action) => action.id),
      expectedBlockedActions(projection.target),
      `${projection.target}: blocked action set drift`
    );
    assert.deepStrictEqual(metadata.capabilityBindings, TARGET_POLICIES[projection.target].capabilities);
    assert.deepStrictEqual(metadata.approvalBindings, TARGET_POLICIES[projection.target].approvals);
    if (projection.target === 'clio') {
      assert.deepStrictEqual(metadata.hostToolEnforcement, {
        actionScoped: false,
        surface: 'clio:session-tools',
        certificationAutonomy: ['read-only', 'suggest'],
        undeclaredToolCall: 'fail'
      });
    } else {
      assert.strictEqual(Object.hasOwn(metadata, 'hostToolEnforcement'), false);
    }
    assert.deepStrictEqual(
      sorted(Object.keys(metadata.effectCapabilityBindings)),
      sorted(readJson(path.join(ROOT, 'protocol', 'effects.json')).effects.map((effect) => effect.id))
    );
    for (const action of metadata.actions) {
      assert.ok(['available', 'unavailable'].includes(action.status));
      assert.deepStrictEqual(action.unavailableCapabilities, sorted(action.unavailableCapabilities));
      assert.deepStrictEqual(action.unavailableEffects, sorted(action.unavailableEffects));
      if (action.status === 'available') {
        assert.deepStrictEqual(action.unavailableCapabilities, []);
        assert.deepStrictEqual(action.unavailableEffects, []);
      }
    }

    for (const skill of catalog.skills) {
      const blockedSkillActions = skill.actions.filter((actionId) => expectedBlockedActions(projection.target).includes(actionId));
      const source = planText(projection.plan, `${projection.skillRoot}/${skill.id}/references/actions.md`);
      for (const actionId of blockedSkillActions) {
        assert.ok(source.includes(`### \`${actionId}\`\n\nWTFP_ACTION_UNAVAILABLE`),
          `${projection.target}:${skill.id}: missing skill-route blocker for ${actionId}`);
        assert.ok(source.includes(`Target: \`${projection.target}\``));
      }
    }
  }
});

record('every envelope exposes only declared tools plus the bounded dispatcher', () => {
  const expected = [
    ...toolsRegistry.map((tool) => `tools/${tool.implementation.slice('wtfp://tools/'.length)}.js`),
    'tools/wtfp-tool.js'
  ].sort((left, right) => left.localeCompare(right));
  for (const target of [...Object.keys(EXPECTED_ROOTS), 'clio']) {
    const plan = plansById.get(target);
    assert.deepStrictEqual(planFiles(plan, /^tools\/.*\.js$/), expected, `${target}: bundled tool surface drift`);
    assert.ok(plan.files.has('tools/README.md'), `${target}: logical tool resolver documentation is missing`);
    for (const sourcePath of expected) {
      const source = planText(plan, sourcePath);
      for (const match of source.matchAll(/require\((?:'|")(\.\.?\/[^'"]+)(?:'|")\)/g)) {
        const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(sourcePath), match[1]));
        assert.ok(plan.files.has(resolved), `${target}:${sourcePath}: undeclared module dependency ${match[1]}`);
      }
    }
    for (const forbidden of ['adapter-compiler.js', 'checkpoint.js', 'context-primer.js', 'manifest.js', 'native-registration.js', 'ownership.js', 'utils.js', 'wcn-compiler.js']) {
      assert.ok(![...plan.files.keys()].some((file) => file === `tools/${forbidden}` || file.endsWith(`/${forbidden}`)), `${target}: unsafe internal tool leaked: ${forbidden}`);
    }
  }
});

record('supported hosts contain exactly 11 generated native roles', () => {
  for (const target of ['clio', 'claude', 'copilot', 'opencode', 'antigravity', 'gemini']) {
    const plan = plansById.get(target);
    const expected = expectedAgentPaths(target);
    const actual = FLAT_AGENT_TARGETS.includes(target)
      ? planFiles(plan, /^agents\/wtfp-[^/]+\.md$/)
      : planFiles(plan, /^agents\/wtfp\/[^/]+\.md$/);
    assert.deepStrictEqual(actual, expected, `${target}: native role surface drift`);
    for (const sourcePath of expected) {
      assert.ok(planText(plan, sourcePath).includes(GENERATED_BANNER), `${target}:${sourcePath}: missing source banner`);
    }
  }
  assert.deepStrictEqual(planFiles(plansById.get('codex'), /^agents\//), [], 'Codex should expose roles through skills, not an invented agent format');
});

record('Claude ships the academic output style, the write guard, and skill-bound agents', () => {
  const plan = plansById.get('claude');
  const style = planText(plan, 'output-styles/wtfp-academic-writing.md');
  assert.match(style, /^name: WTF-P Academic Writing$/m);
  assert.match(style, /^keep-coding-instructions: false$/m);
  assert.doesNotMatch(style, /force-for-plugin/, 'the style must stay selectable, never forced');
  for (const skill of EXPECTED_SKILLS) assert.ok(style.includes(`\`${skill}\``), `output style omits ${skill}`);
  for (const actionId of actionIds) assert.ok(style.includes(`/wtfp:${actionId}`), `output style omits /wtfp:${actionId}`);

  const hooks = JSON.parse(planText(plan, 'hooks/hooks.json'));
  const guard = JSON.parse(planText(plan, 'scripts/write-guard.json'));
  const script = planText(plan, 'scripts/wtfp-write-guard.js');
  assert.ok(script.startsWith('// Generated by WTF-P adapter compiler'));
  const guarded = sorted(Object.keys(guard.actions));
  const expectedGuarded = sorted(actionIds.filter((id) => {
    const action = readJson(path.join(ROOT, 'protocol/actions', `${id}.json`));
    return action.produces.some((output) => output.uri.startsWith('project://paper'));
  }));
  assert.deepStrictEqual(guarded, expectedGuarded, 'guard covers exactly the manuscript-writing actions');
  for (const roots of Object.values(guard.actions)) assert.deepStrictEqual(roots, ['.planning', 'paper']);
  assert.strictEqual(hooks.hooks.UserPromptExpansion[0].matcher, `^wtfp:(${guarded.join('|')})$`);
  assert.strictEqual(hooks.hooks.PreToolUse[0].matcher, 'Write|Edit|MultiEdit|NotebookEdit');
  assert.ok(Array.isArray(hooks.hooks.Stop) && hooks.hooks.Stop.length === 1);
  for (const event of Object.values(hooks.hooks)) {
    for (const entry of event) for (const hook of entry.hooks) {
      assert.match(hook.command, /^node "\$\{CLAUDE_PLUGIN_ROOT\}\/scripts\/wtfp-write-guard\.js" (arm|check|disarm)$/);
    }
  }

  for (const role of EXPECTED_ROLES) {
    const body = planText(plan, `agents/wtfp-${role}.md`);
    assert.match(body, new RegExp(`^skills:\\n  - wtfp:${CLIO_ROLE_SKILLS[role]}$`, 'm'), `${role}: agent must preload its bound plugin skill`);
  }
  for (const role of EXPECTED_ROLES) {
    const opencode = planText(plansById.get('opencode'), `agents/wtfp/${role}.md`);
    assert.match(opencode, /^mode: subagent$/m);
    const gemini = planText(plansById.get('gemini'), `agents/wtfp-${role}.md`);
    assert.match(gemini, /^kind: local$/m);
    assert.doesNotMatch(gemini, /^(tools|allowed-tools|mode|skills):/m, `${role}: Gemini agent schema is strict`);
    const antigravity = planText(plansById.get('antigravity'), `agents/wtfp-${role}.md`);
    assert.match(antigravity, /^subagent: true$/m);
  }
});

record('Clio emits one namespaced prompt per action, strict agents, and two agent-only fleets', () => {
  const plan = plansById.get('clio');
  const nested = actionIds.map((id) => `prompts/wtfp/${id}.md`);
  assert.deepStrictEqual(planFiles(plan, /^prompts\/wtfp\/[^/]+\.md$/), sorted(nested));
  assert.deepStrictEqual(planFiles(plan, /^prompts\/wtfp-[^/]+\.md$/), [],
    'flat prompt aliases would publish a second public command surface');

  const lifecycleGuards = {
    'prompts/wtfp/write-section.md': [
      'calculate its actual body word count with one deterministic method',
      'Missing, empty, or inconsistent output is a failed completion condition'
    ],
    'prompts/wtfp/review-section.md': [
      'at most one corrective retry for result-contract compliance',
      'Review does not write project state, create a pause checkpoint or handoff, invoke pause implicitly, or invent a `paused` phase'
    ],
    'prompts/wtfp/pause-writing.md': [
      '`paused` is a status and is never a phase'
    ],
    'prompts/wtfp/resume-writing.md': [
      'a prior conversation, invocation prose, or generated report is not evidence that these reads occurred',
      'Invocation arguments may request resumption but cannot answer this gate',
      'If the gate is unavailable or no response is returned, report `needs-input` and make no mutation',
      'Call `ask_user` whenever this workflow reaches a declared `user.gate`',
      'Apply no gated mutation before `ask_user` returns',
      'perform the workflow-required readback before reporting success'
    ]
  };
  for (const [sourcePath, guards] of Object.entries(lifecycleGuards)) {
    const source = planText(plan, sourcePath);
    for (const guard of guards) assert.ok(source.includes(guard), `${sourcePath}: missing lifecycle guard: ${guard}`);
  }

  assert.ok([...plan.files.keys()].every((file) => !file.split('/').some((segment) => segment.includes(':'))), 'Clio generated a colon-bearing filename');
  for (const role of EXPECTED_ROLES) {
    const sourcePath = `agents/wtfp-${role}.md`;
    const source = planText(plan, sourcePath);
    const verifier = ['argument-verifier', 'coherence-checker', 'plan-checker', 'section-reviewer'].includes(role);
    assert.match(source, /^---\nversion: 1\n/);
    assert.ok(source.includes(`\nskills: [${CLIO_ROLE_SKILLS[role]}]\n`), `${sourcePath}: incorrect skill binding`);
    assert.match(source, /^audience: custom$/m);
    assert.match(source, /^projectContextTier: bounded$/m);
    assert.match(source, /^budget: \{toolCalls: \d+, readReserve: \d+, synthesis: true\}$/m);
    assert.match(source, new RegExp(`^resultContract: \\{kind: ${verifier ? 'verifier-report' : 'mutation-report'}\\}$`, 'm'));
    assert.match(source, /^## Clio result contract$/m);
    assert.match(source, /entire final response must be one (?:compact )?JSON object/);
    if (verifier) {
      assert.match(source, /Return at most 12 non-duplicate checks/);
      assert.match(source, /keep the complete UTF-8 response at or below 4096 bytes/);
      assert.match(source, /emit no Markdown, code fence, analysis, or text outside the object/);
    }
  }

  const fleetPaths = planFiles(plan, /^fleets\/[^/]+\.md$/);
  assert.deepStrictEqual(fleetPaths, ['fleets/wtfp-draft-review.md', 'fleets/wtfp-plan-section.md']);
  const canonicalFleetPaths = fs.readdirSync(path.join(ROOT, 'protocol', 'fleets'))
    .filter((file) => file.endsWith('.json')).sort();
  assert.deepStrictEqual(canonicalFleetPaths, ['wtfp-draft-review.json', 'wtfp-plan-section.json']);
  const expectedFleetAgents = {
    'fleets/wtfp-draft-review.md': ['wtfp-section-writer', 'wtfp-section-reviewer'],
    'fleets/wtfp-plan-section.md': ['wtfp-section-planner', 'wtfp-plan-checker']
  };
  const expectedFleetWrites = {
    'fleets/wtfp-draft-review.md': 'writes: [paper/, .planning/]',
    'fleets/wtfp-plan-section.md': 'writes: [.planning/]'
  };
  const expectedCanonicalStepWrites = {
    'fleets/wtfp-draft-review.md': [
      ['project://paper/{artifact}', 'project://sections/{section}/summary'],
      []
    ],
    'fleets/wtfp-plan-section.md': [
      ['project://sections/{section}/plans/{plan}'],
      []
    ]
  };
  const expectedFleetInstructions = {
    'fleets/wtfp-draft-review.md': [
      'update only its declared portable Markdown summary',
      'independently review',
      'resolve logical `project://paper/...` artifacts under the project-root `paper/` directory',
      'never under `.planning/paper/`'
    ],
    'fleets/wtfp-plan-section.md': ['support for every required claim', 'independently review']
  };
  for (const sourcePath of fleetPaths) {
    const source = planText(plan, sourcePath);
    const fleetId = path.basename(sourcePath, '.md');
    const canonical = JSON.parse(fs.readFileSync(
      path.join(ROOT, 'protocol', 'fleets', `${fleetId}.json`), 'utf8'
    ));
    assert.strictEqual(canonical.schema, 'wtfp.fleet/v1');
    assert.strictEqual(canonical.id, fleetId);
    assert(canonical.parameters.some(parameter => parameter.id === 'section' && parameter.required));
    assert(canonical.steps.every(step => /^role:\/\//u.test(step.role)));
    assert.deepStrictEqual(
      canonical.steps.map(step => step.writes),
      expectedCanonicalStepWrites[sourcePath],
      `${fleetId}: canonical fleet widened a specialist role's semantic write boundary`
    );
    assert(canonical.steps.flatMap(step => step.writes).every(resource => /^project:\/\//u.test(resource)));
    assert.doesNotMatch(
      JSON.stringify(canonical),
      /(?:"(?:\.planning\/|paper\/)"|"scope"|"agent"|"maxWorkers"|"onFailure"|\{\{section\}\})/u,
      `${fleetId}: canonical fleet leaked a native syntax or physical resource root`
    );
    assert.match(source, /^---\nversion: 4\n/);
    assert.ok(source.includes(
      `<!-- Generated by WTF-P adapter compiler v${GENERATOR_VERSION} from protocol/fleets/${fleetId}.json; do not edit. -->`
    ), `${sourcePath}: generated fleet has false provenance`);
    assert.ok(source.includes(GENERATED_BANNER), `${sourcePath}: missing source banner`);
    assert.ok(source.includes(expectedFleetWrites[sourcePath]), `${sourcePath}: directory write boundary lost its trailing slash`);
    for (const phrase of expectedFleetInstructions[sourcePath]) {
      assert.ok(source.includes(phrase), `${sourcePath}: required native instruction is missing ${phrase}`);
    }
    assert.match(source, /invoking action orchestrator owns/u,
      `${sourcePath}: generated fleet does not reserve approval and state reconciliation to the orchestrator`);
    assert.doesNotMatch(source, /evidence coverage/u,
      `${sourcePath}: Clio 0.3.8 misclassifies the verifier task as a mutating test`);
    assert.doesNotMatch(
      source,
      /writes: \[(?:paper, )?\.planning\]/,
      `${sourcePath}: a bare path is one exact file in Clio's write-boundary grammar`
    );
    assert.doesNotMatch(source, /^\s*- kind: code$/m, `${sourcePath}: initial Clio fleets must remain agent-only`);
    const agents = [...source.matchAll(/^\s+agent: (wtfp-[a-z0-9-]+)$/gm)].map((match) => match[1]);
    assert.deepStrictEqual(agents, expectedFleetAgents[sourcePath]);
    for (const agent of agents) assert.ok(plan.files.has(`agents/${agent}.md`), `${sourcePath}: missing bound agent ${agent}`);
  }
});

record('bound logical tools grant one dispatcher command and unbound ones fail closed', () => {
  const executableActionIds = actionIds.filter(id =>
    readJson(path.join(ROOT, 'protocol', 'actions', `${id}.json`))
      .requirements.capabilities.includes('tool.execute')
  );
  assert(executableActionIds.length > 0, 'fixture must cover logical tool execution');
  for (const actionId of executableActionIds) {
    // Claude and Clio bind `tool.execute`. The grant is Bash, and the only
    // command the workflow authorises is the packaged dispatcher.
    const claude = planText(plansById.get('claude'), `commands/${actionId}.md`);
    assert.doesNotMatch(claude, /^WTFP_ACTION_UNAVAILABLE$/m);
    assert.match(claude, /^\s*- Bash$/m, `${actionId}: bound logical tool did not receive Claude Bash`);
    assert.ok(claude.includes('${CLAUDE_PLUGIN_ROOT}/tools/wtfp-tool.js'),
      `${actionId}: Claude command does not name the bundled dispatcher`);
    assert.ok(claude.includes('Never execute another module in this package'),
      `${actionId}: Claude command does not bound the shell grant`);

    const clio = planText(plansById.get('clio'), `prompts/wtfp/${actionId}.md`);
    assert.doesNotMatch(clio, /^WTFP_ACTION_UNAVAILABLE$/m);
    assert.ok(clio.includes('${pluginRoot}/tools/wtfp-tool.js'),
      `${actionId}: Clio prompt does not name the bundled dispatcher`);

    // Every target without a verified shell tool name stays fail-closed.
    for (const target of ['antigravity', 'copilot', 'gemini', 'opencode']) {
      const [sourcePath] = commandPaths(target, [actionId]);
      const source = planText(plansById.get(target), sourcePath);
      assert.match(source, /^WTFP_ACTION_UNAVAILABLE$/m, `${target}:${actionId}: unbound logical tool did not fail closed`);
      assert.doesNotMatch(source, /^\s*- Bash$/m, `${target}:${actionId}: logical tool widened to a host shell`);
    }
    const copilot = planText(
      plansById.get('copilot-marketplace'),
      `project/.github/prompts/wtfp-${actionId}.prompt.md`
    );
    const tools = copilot.match(/^tools: (.+)$/m)?.[1] || '[]';
    assert.deepStrictEqual(JSON.parse(tools), [], `${actionId}: logical tool widened to Copilot tools`);
    assert.match(copilot, /^WTFP_ACTION_UNAVAILABLE$/m);
  }
});

record('Copilot carries a committed cloud-safe repository projection', () => {
  const plan = plansById.get('copilot-marketplace');
  const prompts = planFiles(plan, /^project\/\.github\/prompts\/wtfp-[^/]+\.prompt\.md$/);
  const agents = planFiles(plan, /^project\/\.github\/agents\/wtfp-[^/]+\.agent\.md$/);
  const skills = planFiles(plan, /^project\/\.github\/skills\/[^/]+\/SKILL\.md$/);
  assert.strictEqual(prompts.length, 36);
  assert.strictEqual(agents.length, 11);
  assert.deepStrictEqual(
    skills,
    EXPECTED_SKILLS.map((skill) => `project/.github/skills/${skill}/SKILL.md`)
  );
  assert.ok(plan.files.has('project/.github/copilot-instructions.md'));
  assert.ok(plan.files.has('project/.github/wtfp/project/README.md'));
  for (const sourcePath of [...prompts, ...agents]) {
    const source = planText(plan, sourcePath);
    assert.ok(source.includes(GENERATED_BANNER), `${sourcePath}: missing provenance`);
    assert.doesNotMatch(source, /\$\{CLAUDE_PLUGIN_ROOT\}/, `${sourcePath}: user-plugin root leaked into cloud projection`);
    assert.doesNotMatch(source, /\$ARGUMENTS/, `${sourcePath}: local-plugin arguments leaked into cloud projection`);
    assert.doesNotMatch(source, /^@\.github\//m, `${sourcePath}: local-plugin include leaked into cloud projection`);
    for (const match of source.matchAll(/\]\(\.\.\/wtfp\/([^)]+)\)/g)) {
      assert.ok(plan.files.has(`project/.github/wtfp/${match[1]}`), `${sourcePath}: unresolved cloud link ${match[0]}`);
    }
  }
  for (const sourcePath of prompts) {
    const source = planText(plan, sourcePath);
    const actionId = path.basename(sourcePath, '.prompt.md').slice('wtfp-'.length);
    if (expectedBlockedActions('copilot-cloud').includes(actionId)) {
      assert.match(source, /^WTFP_ACTION_UNAVAILABLE$/m, `${sourcePath}: missing blocked marker`);
      assert.match(source, /^tools: \[\]$/m, `${sourcePath}: blocked cloud action did not explicitly deny tools`);
      assert.doesNotMatch(source, /\$\{input:arguments:/, `${sourcePath}: blocked cloud action received input`);
      continue;
    }
    assert.match(
      source,
      /\$\{input:arguments:Describe the requested WTF-P action input\}/,
      `${sourcePath}: missing Copilot input variable`
    );
    assert.match(source, /^tools: \[[^\n]+\]$/m, `${sourcePath}: missing bounded Copilot tools`);
  }
  for (const actionId of GATED_NETWORK_ACTIONS) {
    const source = planText(plan, `project/.github/prompts/wtfp-${actionId}.prompt.md`);
    assert.match(source, /^tools: \[\]$/m, `${actionId}: gated cloud network action did not deny all tools`);
    assert.doesNotMatch(source, /^tools: .*"web"/m, `${actionId}: gated cloud network action exposed web`);
  }
});

record('Codex, Claude, Copilot, Antigravity, Gemini, and plugin manifests resolve locally', () => {
  const codex = plansById.get('codex');
  const codexManifest = JSON.parse(planText(codex, '.codex-plugin/plugin.json'));
  assert.strictEqual(codexManifest.name, 'wtf-p');
  assert.strictEqual(codexManifest.version, PACKAGE_VERSION);
  assert.ok(codexManifest.description);
  assert.strictEqual(codexManifest.skills, './skills/');
  assert.ok(codexManifest.interface && codexManifest.interface.displayName === 'WTF-P');
  assertManifestDirectory(codex, codexManifest.skills, 'Codex skills');

  for (const target of ['claude', 'copilot']) {
    const plan = plansById.get(target);
    const manifest = JSON.parse(planText(plan, '.claude-plugin/plugin.json'));
    assert.strictEqual(manifest.name, target === 'claude' ? 'wtfp' : 'wtf-p');
    assert.strictEqual(manifest.version, PACKAGE_VERSION);
    assert.ok(manifest.description, `${target}: plugin manifest needs a description`);
    for (const resource of ['commands', 'agents', 'skills']) assertDirectory(plan, resource, `${target} ${resource}`);
  }

  const claudeMarketplace = JSON.parse(planText(plansById.get('claude'), '.claude-plugin/marketplace.json'));
  assert.strictEqual(claudeMarketplace.name, 'wtfp');
  assert.strictEqual(claudeMarketplace.plugins[0].name, 'wtfp');
  assert.strictEqual(claudeMarketplace.plugins[0].source, './');

  const antigravity = plansById.get('antigravity');
  // Antigravity's published manifest schema allows exactly name and
  // description; components are discovered from fixed directories.
  const antigravityManifest = JSON.parse(planText(antigravity, 'plugin.json'));
  assert.deepStrictEqual(sorted(Object.keys(antigravityManifest)), ['$schema', 'description', 'name']);
  assert.strictEqual(antigravityManifest.name, 'wtf-p');
  assert.ok(antigravityManifest.description.includes(PACKAGE_VERSION));
  for (const resource of ['commands', 'agents', 'skills', 'rules']) assertDirectory(antigravity, resource, `Antigravity ${resource}`);
  assert.ok(planText(antigravity, 'rules/wtfp-project-state.md').includes('project://manifest'));

  const gemini = plansById.get('gemini');
  const geminiManifest = JSON.parse(planText(gemini, 'gemini-extension.json'));
  assert.strictEqual(geminiManifest.version, PACKAGE_VERSION);
  assert.ok(gemini.files.has(geminiManifest.contextFileName), 'Gemini contextFileName does not resolve');

  const pluginPlan = plansById.get('portable-plugin');
  const clioExtension = JSON.parse(planText(pluginPlan, 'plugin.json')).extensions['ai.iowarp.clio'];
  assert.strictEqual(clioExtension.manifestVersion, 1);
  assert.strictEqual(clioExtension.compatibility.clio, '>=0.4.7');
  assert.deepStrictEqual(clioExtension.resources, {
    skills: 'skills',
    prompts: 'ai.iowarp.clio/prompts',
    agents: 'ai.iowarp.clio/agents',
    fleets: 'ai.iowarp.clio/fleets'
  });
  for (const directory of Object.values(clioExtension.resources)) {
    assertDirectory(pluginPlan, directory, `Clio ${directory}`);
  }
  assert.deepStrictEqual(planFiles(pluginPlan, /^ai\.iowarp\.clio\/prompts\/[^/]+\.md$/), [],
    'the canonical plugin must publish no flat prompt aliases');

  const codexMarketplace = JSON.parse(planText(
    plansById.get('codex-marketplace'),
    '.agents/plugins/marketplace.json'
  ));
  assert.deepStrictEqual(codexMarketplace.plugins[0].source, { source: 'local', path: './plugins/wtf-p' });
  assert.ok(plansById.get('codex').root.startsWith(`${plansById.get('codex-marketplace').root}${path.sep}`));

  const copilotMarketplace = JSON.parse(planText(plansById.get('copilot-marketplace'), 'marketplace.json'));
  assert.strictEqual(copilotMarketplace.plugins[0].source, './plugins/wtf-p');
  assert.ok(plansById.get('copilot').root.startsWith(`${plansById.get('copilot-marketplace').root}${path.sep}`));
});

record('every bundled native resource reference resolves inside its target envelope', () => {
  for (const target of ['clio', 'claude', 'copilot', 'opencode', 'antigravity', 'gemini']) {
    const plan = plansById.get(target);
    const nativePaths = [
      ...commandPaths(target, actionIds),
      ...expectedAgentPaths(target)
    ];
    assertSelfContained(plan, nativePaths, ['clio', 'claude', 'copilot', 'antigravity'].includes(target));
    if (target === 'claude') assertSelfContained(plan, ['output-styles/wtfp-academic-writing.md'], true);
    if (target === 'gemini') {
      for (const sourcePath of nativePaths) {
        assert.doesNotMatch(planText(plan, sourcePath), /\$\{extensionPath\}/, `${sourcePath}: unsupported Gemini prompt variable`);
      }
    }
  }
});

record('standard plugin graph resolves and retains portable host boundaries', () => {
  const plan = plansById.get('portable-plugin');
  const manifest = JSON.parse(planText(plan, 'plugin.json'));
  assert.strictEqual(manifest.$schema, 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json');
  assert.strictEqual(manifest.name, 'wtfp');
  assert.strictEqual(manifest.version, PACKAGE_VERSION);
  const { SchemaRegistry, validateInstance } = require('../evaluation/lib/json-schema');
  const schemaFile = path.join(ROOT, 'test/fixtures/agent-plugin-1.0.0.schema.json');
  const registry = new SchemaRegistry([schemaFile]);
  assert.deepStrictEqual(validateInstance(manifest, registry.get(schemaFile), schemaFile, registry), []);
  assert.ok(validateInstance({ ...manifest, skills: './skills' }, registry.get(schemaFile), schemaFile, registry).length, 'nonstandard top-level metadata must fail');
  const extension = manifest.extensions['ai.iowarp.clio'];
  const components = new Map(extension.components.map(item => [`${item.kind}:${item.id}`, item]));
  assert.strictEqual(components.size, 56);
  for (const [ref, item] of components) {
    assert.ok(plan.files.has(item.path), `${ref} has no packaged file`);
    for (const dependency of item.requires) assert.ok(components.has(dependency), `${ref}: missing ${dependency}`);
    if (['agent', 'fleet', 'prompt'].includes(item.kind)) assert.ok(item.path.startsWith('ai.iowarp.clio/'));
  }
  assertSkillLinksResolve(plan);
  for (const directory of Object.values(extension.resources)) assert.ok([...plan.files.keys()].some(file => file.startsWith(directory + '/')));
  const codex = plansById.get('codex');
  const standard = JSON.parse(planText(codex, 'plugin.json'));
  const fallback = JSON.parse(planText(codex, '.codex-plugin/plugin.json'));
  for (const field of ['name', 'version']) assert.strictEqual(standard[field], fallback[field]);
});

record('research handoff declares incremental state and preserves native decision returns', () => {
  const action = readJson(path.join(ROOT, 'protocol/actions/map-project.json'));
  for (const uri of ['project://sources/{source}', 'project://evidence/{evidence}', 'project://manifest']) {
    assert.ok(action.reads.includes(uri));
    assert.ok(action.produces.some(output => output.uri === uri && output.mode === 'update'));
  }
  for (const target of Object.keys(EXPECTED_ROOTS)) {
    const plan = plansById.get(target);
    const role = planText(plan, 'roles/outliner.md');
    assert.match(role, /sum equals the approved target exactly/);
    assert.doesNotMatch(role, /within ten percent/);
    const mapping = planText(plan, 'skills/wtfp-start-project/references/actions.md');
    assert.match(mapping, /Read existing source and evidence records before any update/);
    assert.match(mapping, /preserving existing entries/);
  }
  const clio = plansById.get('clio');
  // Clio has no native web-search tool. The only scholarly search WTF-P declares
  // is the bundled citation client, run through the packaged dispatcher.
  assert.strictEqual(TARGET_POLICIES.clio.capabilities['network.search'], 'clio:bash-bundled-citation-tools');
  assert.strictEqual(TARGET_POLICIES.clio.capabilities['tool.execute'], 'clio:bash');
  assert.strictEqual(TARGET_POLICIES.claude.capabilities['tool.execute'], 'claude:Bash');
  for (const target of ['antigravity', 'codex', 'copilot', 'copilot-cloud', 'gemini', 'opencode']) {
    assert.strictEqual(TARGET_POLICIES[target].capabilities['tool.execute'], null,
      `${target}: tool.execute must stay fail-closed until its shell tool name is verified`);
  }
  for (const role of EXPECTED_ROLES) {
    const body = planText(clio, `agents/wtfp-${role}.md`);
    assert.match(body, /entry named wtfp.role-result/);
    assert.match(body, /status needs_input/);
    assert.match(body, /Embedded portable result schema:/);
  }
  assert.match(planText(clio, 'prompts/wtfp/create-outline.md'), /Missing, duplicate or malformed outcomes fail closed/);
  for (const role of EXPECTED_ROLES) {
    const body = planText(plansById.get('claude'), `agents/wtfp-${role}.md`);
    assert.match(body, /^tools:$/m);
    assert.doesNotMatch(body, /^allowed-tools:/m);
  }
});

if (failures.length > 0) {
  process.stderr.write(`\n${failures.length} adapter compiler contract(s) failed; ${passed} passed.\n`);
  process.exitCode = 1;
} else {
  process.stdout.write(`\n${passed} adapter compiler contracts passed.\n`);
}
