#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const GENERATED = 'Generated by WTF-P adapter compiler v';
const failures = [];
let passed = 0;

function relative(filePath) {
  return path.relative(ROOT, filePath).split(path.sep).join('/');
}

function fail(filePath, message) {
  failures.push(`${relative(filePath)}: ${message}`);
}

function check(condition, filePath, message) {
  if (!condition) fail(filePath, message);
}

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return null;
  const fields = {};
  for (const line of match[1].split('\n')) {
    const field = line.match(/^([a-z_][a-z0-9_-]*):\s*(.*)$/i);
    if (field && field[2]) fields[field[1]] = field[2];
  }
  return { fields, body: match[2] };
}

function readRequired(filePath) {
  if (!fs.existsSync(filePath)) {
    fail(filePath, 'required generated resource is missing');
    return null;
  }
  return fs.readFileSync(filePath, 'utf8');
}

function validateMarkdownCommand(filePath, actionId, options) {
  const content = readRequired(filePath);
  if (content === null) return;
  const parsed = parseFrontmatter(content);
  if (!parsed) {
    fail(filePath, 'missing or invalid YAML frontmatter');
    return;
  }

  check(Boolean(parsed.fields.description), filePath, 'description is required');
  if (options.pathDerivedName) {
    check(!Object.hasOwn(parsed.fields, 'name'), filePath, 'host derives the canonical name from plugin and file path');
  } else if (options.frontmatterName) {
    check(parsed.fields.name === `wtfp:${actionId}`, filePath, `name must be wtfp:${actionId}`);
  }
  check(content.includes(GENERATED), filePath, 'compiler provenance banner is missing');
  check(/^## Record contract$/m.test(parsed.body), filePath, 'portable record contract is missing');
  check(/^## Procedure$/m.test(parsed.body), filePath, 'action procedure is missing');
  check(/^## Safety and completion$/m.test(parsed.body), filePath, 'safety/completion contract is missing');
  check(/^## Invocation input$/m.test(parsed.body), filePath, 'invocation input block is missing');
  check(parsed.body.includes('$ARGUMENTS'), filePath, 'native argument placeholder is missing');
  check(!/^@protocol:\/\//m.test(parsed.body), filePath, 'portable include was not rendered for the host');
  passed++;
}

function parseTomlCommand(content) {
  const description = content.match(/^description\s*=\s*"([^"]+)"$/m)?.[1];
  const prompt = content.match(/^prompt\s*=\s*'''\n([\s\S]*?)\n'''\s*$/m)?.[1];
  return { description, prompt };
}

function validateGeminiCommand(filePath) {
  const content = readRequired(filePath);
  if (content === null) return;
  const parsed = parseTomlCommand(content);
  check(Boolean(parsed.description), filePath, 'TOML description is required');
  if (!parsed.prompt) {
    fail(filePath, 'TOML prompt literal is missing or malformed');
    return;
  }
  check(parsed.prompt.includes(GENERATED), filePath, 'compiler provenance banner is missing');
  check(/^## Record contract$/m.test(parsed.prompt), filePath, 'portable record contract is missing');
  check(/^## Procedure$/m.test(parsed.prompt), filePath, 'action procedure is missing');
  check(/^## Safety and completion$/m.test(parsed.prompt), filePath, 'safety/completion contract is missing');
  check(/^## Invocation input$/m.test(parsed.prompt), filePath, 'invocation input block is missing');
  check(parsed.prompt.includes('{{args}}'), filePath, 'Gemini argument placeholder is missing');
  check(!/^@protocol:\/\//m.test(parsed.prompt), filePath, 'portable include was not embedded');
  check(!parsed.prompt.includes('${extensionPath}'), filePath, 'extensionPath is not expanded inside Gemini TOML prompts');
  passed++;
}

function validateAgent(filePath, roleId) {
  const content = readRequired(filePath);
  if (content === null) return;
  const parsed = parseFrontmatter(content);
  if (!parsed) {
    fail(filePath, 'missing or invalid YAML frontmatter');
    return;
  }
  check(Boolean(parsed.fields.name), filePath, 'agent name is required');
  check(Boolean(parsed.fields.description), filePath, 'agent description is required');
  check(content.includes(GENERATED), filePath, 'compiler provenance banner is missing');
  check(/^#\s+\S+/m.test(parsed.body), filePath, 'agent role heading is missing');
  check(/result contract/i.test(parsed.body), filePath, 'portable or native result contract is missing');
  check(!/^@protocol:\/\//m.test(parsed.body), filePath, 'portable include was not rendered for the host');
  if (filePath.includes(`${path.sep}opencode${path.sep}`) || filePath.includes(`${path.sep}gemini${path.sep}`)) {
    check(
      content.includes('data-wtfp-source="protocol://schemas/role-result.schema.json"'),
      filePath,
      `${roleId} does not embed its portable result schema`,
    );
  }
  passed++;
}

function validateLegacyWorkflow(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  check(content.trim().length > 0, filePath, 'legacy compatibility workflow is empty');
  const openSteps = (content.match(/<step(?:\s|>)/g) || []).length;
  const closeSteps = (content.match(/<\/step>/g) || []).length;
  check(openSteps === closeSteps, filePath, `mismatched step tags (${openSteps} open, ${closeSteps} closed)`);
  passed++;
}

const aliases = JSON.parse(fs.readFileSync(path.join(ROOT, 'protocol', 'aliases.lock.json'), 'utf8')).aliases;
const actionIds = aliases.map((entry) => entry.action);
const roleIds = fs.readdirSync(path.join(ROOT, 'protocol', 'roles'))
  .filter((file) => file.endsWith('.md'))
  .map((file) => path.basename(file, '.md'))
  .sort((left, right) => left.localeCompare(right));

const markdownCommands = [
  {
    target: 'claude',
    pathFor: (id) => `vendors/claude/commands/${id}.md`,
    options: { pathDerivedName: true },
  },
  {
    target: 'clio-nested',
    pathFor: (id) => `vendors/clio/prompts/wtfp/${id}.md`,
    options: {},
  },
  {
    target: 'clio-flat',
    pathFor: (id) => `vendors/clio/prompts/wtfp-${id}.md`,
    options: {},
  },
  {
    target: 'copilot',
    pathFor: (id) => `vendors/copilot/plugins/wtf-p/commands/wtfp-${id}.md`,
    options: { frontmatterName: true },
  },
  {
    target: 'opencode',
    pathFor: (id) => `vendors/opencode/commands/wtfp/${id}.md`,
    options: { frontmatterName: true },
  },
  {
    target: 'antigravity',
    pathFor: (id) => `vendors/antigravity/commands/wtfp-${id}.md`,
    options: { frontmatterName: true },
  },
];

for (const commandTarget of markdownCommands) {
  for (const actionId of actionIds) {
    validateMarkdownCommand(path.join(ROOT, commandTarget.pathFor(actionId)), actionId, commandTarget.options);
  }
}
for (const actionId of actionIds) {
  validateGeminiCommand(path.join(ROOT, 'vendors', 'gemini', 'commands', 'wtfp', `${actionId}.toml`));
}

const agentTargets = [
  { pathFor: (id) => `vendors/clio/agents/wtfp-${id}.md` },
  { pathFor: (id) => `vendors/claude/agents/wtfp/${id}.md` },
  { pathFor: (id) => `vendors/copilot/plugins/wtf-p/agents/wtfp-${id}.md` },
  { pathFor: (id) => `vendors/opencode/agents/wtfp/${id}.md` },
  { pathFor: (id) => `vendors/antigravity/agents/wtfp-${id}.md` },
  { pathFor: (id) => `vendors/gemini/agents/wtfp/${id}.md` },
];
for (const agentTarget of agentTargets) {
  for (const roleId of roleIds) validateAgent(path.join(ROOT, agentTarget.pathFor(roleId)), roleId);
}

const legacyWorkflowRoot = path.join(ROOT, 'core', 'write-the-f-paper', 'workflows');
for (const file of fs.readdirSync(legacyWorkflowRoot).sort()) {
  if (file.endsWith('.md') && !file.endsWith('.wcn.md')) validateLegacyWorkflow(path.join(legacyWorkflowRoot, file));
}

if (failures.length > 0) {
  for (const failure of failures) process.stderr.write(`\x1b[31mFAIL\x1b[0m ${failure}\n`);
  process.stderr.write(`\nContent linter failed: ${failures.length} defects; ${passed} resources inspected.\n`);
  process.exit(1);
}

process.stdout.write(`Content linter passed: ${passed} native and compatibility resources inspected.\n`);
