#!/usr/bin/env node
'use strict';

// The generated tools/wtfp-tool.js is the one command a host is ever asked to
// run. These contracts pin its bounds against the packaged copy in the
// canonical plugin bundle.

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const DISPATCHER = path.join(ROOT, 'vendors', 'plugin', 'tools', 'wtfp-tool.js');
const registry = JSON.parse(fs.readFileSync(path.join(ROOT, 'protocol', 'tools.json'), 'utf8'));
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'wtfp-tool-dispatcher-'));
let passed = 0;

function test(name, fn) { fn(); passed += 1; console.log(`✓ ${name}`); }
function run(args, env = {}) {
  return spawnSync(process.execPath, [DISPATCHER, ...args], {
    cwd: scratch,
    env: { ...process.env, ...env },
    encoding: 'utf8',
    timeout: 30000
  });
}
function errorOf(result) {
  assert.strictEqual(result.status, 1, result.stdout + result.stderr);
  assert.strictEqual(result.stdout, '');
  return JSON.parse(result.stderr).error;
}

const bib = path.join(scratch, 'refs.bib');
fs.writeFileSync(bib, '@article{k1,\n  title={A title},\n  author={Someone},\n  year={2020}\n}\n');
const link = path.join(scratch, 'link.bib');
fs.symlinkSync(bib, link);

try {
  test('every packaged .js carries a // banner, never an HTML comment', () => {
    const toolsRoot = path.join(ROOT, 'vendors', 'plugin', 'tools');
    const visit = (dir) => {
      for (const name of fs.readdirSync(dir)) {
        const file = path.join(dir, name);
        if (fs.statSync(file).isDirectory()) { visit(file); continue; }
        if (!name.endsWith('.js')) continue;
        const source = fs.readFileSync(file, 'utf8');
        assert.ok(!source.includes('<!--'), `${file} carries an HTML comment`);
      }
    };
    visit(toolsRoot);
    const head = fs.readFileSync(DISPATCHER, 'utf8').split('\n').slice(0, 6).join('\n');
    assert.match(head, /^\/\/ Generated by WTF-P adapter compiler v\d+ from protocol\/tools\.json; do not edit\.$/m);
  });

  test('the dispatcher parses as an ES module as well as a CommonJS script', () => {
    const result = spawnSync(process.execPath, ['--input-type=module', '-e', `import(${JSON.stringify(DISPATCHER)});`], {
      cwd: scratch, encoding: 'utf8', timeout: 30000
    });
    assert.strictEqual(result.status, 0, result.stderr);
    assert.strictEqual(JSON.parse(result.stdout).tool, 'wtfp-tool');
  });

  test('list projects the declared effects of every command from protocol/tools.json', () => {
    const result = run(['list']);
    assert.strictEqual(result.status, 0, result.stderr);
    const listing = JSON.parse(result.stdout);
    assert.strictEqual(listing.offline, false);
    assert.strictEqual(listing.commands.length, registry.tools.length);
    for (const entry of listing.commands) {
      const tool = registry.tools.find((candidate) => candidate.id === entry.tool);
      assert.ok(tool, `${entry.command} names an undeclared tool`);
      assert.deepStrictEqual(entry.effects, tool.effects);
    }
    assert.strictEqual(JSON.parse(run(['--offline', 'list']).stdout).offline, true);
  });

  test('offline mode refuses exactly the commands that declare a network effect', () => {
    const listing = JSON.parse(run(['list']).stdout);
    for (const entry of listing.commands) {
      const networked = entry.effects.some((effect) => effect.startsWith('network.'));
      const viaFlag = run(['--offline', entry.command, bib]);
      const viaEnv = run([entry.command, bib], { WTFP_TOOL_OFFLINE: '1' });
      if (networked) {
        assert.match(errorOf(viaFlag), /refused in offline mode/, entry.command);
        assert.match(errorOf(viaEnv), /refused in offline mode/, entry.command);
      } else {
        assert.ok(!/offline/.test(viaFlag.stderr), `${entry.command} must run offline`);
        assert.ok(!/offline/.test(viaEnv.stderr), `${entry.command} must run offline`);
      }
    }
    assert.strictEqual(run(['--offline', 'bib-index', bib]).status, 0);
  });

  test('a symlinked bibliography is read through its resolved target', () => {
    const direct = run(['--offline', 'bib-index', bib]);
    const viaLink = run(['--offline', 'bib-index', link]);
    assert.strictEqual(viaLink.status, 0, viaLink.stderr);
    assert.deepStrictEqual(JSON.parse(viaLink.stdout), JSON.parse(direct.stdout));
    assert.match(errorOf(run(['--offline', 'bib-index', scratch])), /not a regular file/);
    assert.match(errorOf(run(['--offline', 'bib-index', path.join(scratch, 'absent.bib')])), /file not found/);
  });

  test('file paths and queries carry separate caps', () => {
    const longPath = path.join(scratch, 'x'.repeat(600));
    assert.match(errorOf(run(['--offline', 'bib-index', longPath])), /file not found/);
    assert.match(errorOf(run(['--offline', 'bib-index', 'y'.repeat(5000)])), /file path exceeds 4096/);
    assert.match(errorOf(run(['--offline', 'bib-index', bib, `--query=${'q'.repeat(513)}`])), /--query exceeds 512/);
  });

  test('<command> --help prints that command and exits 0', () => {
    for (const command of ['bib-index', 'bib-impact', 's2-search']) {
      for (const flag of ['--help', '-h']) {
        const result = run([command, flag]);
        assert.strictEqual(result.status, 0, result.stderr);
        const printed = JSON.parse(result.stdout);
        assert.strictEqual(printed.command, command);
        assert.ok(Array.isArray(printed.effects));
        assert.match(printed.usage, new RegExp(`^${command} `));
      }
    }
    assert.match(errorOf(run(['nonsense', '--help'])), /unknown command/);
  });

  test('bib-index reports duplicate keys and refuses an ambiguous --key', () => {
    const dup = path.join(scratch, 'dup.bib');
    fs.writeFileSync(dup, '@article{k1,\n  title={A},\n  year={2020}\n}\n@article{k1,\n  title={A2},\n  year={2021}\n}\n@misc{k2,\n  title={Only},\n  year={2019}\n}\n');
    const listing = JSON.parse(run(['--offline', 'bib-index', dup]).stdout);
    assert.deepStrictEqual(listing.duplicates, [{ key: 'k1', count: 2 }]);
    assert.deepStrictEqual(listing.entries.map((entry) => entry.duplicate === true), [true, true, false]);
    assert.match(errorOf(run(['--offline', 'bib-index', dup, '--key=k1'])), /ambiguous: k1 appears 2 times/);
    assert.match(errorOf(run(['--offline', 'bib-format', dup, '--key=k1'])), /ambiguous/);
    assert.strictEqual(JSON.parse(run(['--offline', 'bib-index', dup, '--key=k2']).stdout).key, 'k2');
    assert.match(errorOf(run(['--offline', 'bib-index', dup, '--key=k9'])), /citation key not found/);
  });

  test('bib-format emits standard BibTeX by default and al-folio only by explicit style', () => {
    const formatted = JSON.parse(run(['--offline', 'bib-format', bib, '--key=k1']).stdout);
    assert.strictEqual(formatted.style, 'bibtex');
    assert.match(formatted.formatted, /^@article\{k1,/);
    assert.ok(!formatted.formatted.includes('entry_type'));
    const alFolio = JSON.parse(run(['--offline', 'bib-format', bib, '--key=k1', '--style=al-folio']).stdout);
    assert.match(alFolio.formatted, /^@journal\{k1,/);
    assert.match(errorOf(run(['--offline', 'bib-format', bib, '--key=k1', '--style=jekyll'])), /--style must be bibtex or al-folio/);
  });

  test('network commands enforce a hard --timeout with exit 124 and report progress on stderr', () => {
    // Copy the packaged tools and stub the impact analyzer so the wall clock,
    // not the network, decides the outcome.
    const copy = path.join(scratch, 'tools');
    fs.cpSync(path.join(ROOT, 'vendors', 'plugin', 'tools'), copy, { recursive: true });
    const stub = path.join(copy, 'bibliography', 'analyze-impact.js');
    assert.ok(fs.existsSync(stub));
    fs.writeFileSync(stub, `module.exports = { analyze: (file, options) => { options.onProgress(5, 10); if (process.env.STUB_RESOLVE) return Promise.resolve({ seminal: [] }); return new Promise(() => {}); } };`);
    const copied = path.join(copy, 'wtfp-tool.js');
    const hung = spawnSync(process.execPath, [copied, 'bib-impact', bib, '--timeout=1'], { cwd: scratch, encoding: 'utf8', timeout: 30000 });
    assert.strictEqual(hung.status, 124, hung.stdout + hung.stderr);
    assert.strictEqual(hung.stdout, '');
    const lines = hung.stderr.trim().split('\n');
    assert.strictEqual(lines[0], 'bib-impact: 5/10 entries queried');
    assert.deepStrictEqual(JSON.parse(lines[lines.length - 1]), { error: 'bib-impact timed out after 1 s' });
    const done = spawnSync(process.execPath, [copied, 'bib-impact', bib, '--timeout=5'], { cwd: scratch, encoding: 'utf8', timeout: 30000, env: { ...process.env, STUB_RESOLVE: '1' } });
    assert.strictEqual(done.status, 0, done.stderr);
    assert.deepStrictEqual(JSON.parse(done.stdout), { seminal: [] });
    for (const bad of ['0', '601', 'soon']) {
      assert.match(errorOf(run(['bib-impact', bib, `--timeout=${bad}`])), /--timeout must be an integer number of seconds between 1 and 600/);
    }
    assert.match(errorOf(run(['--offline', 'bib-impact', bib, '--timeout=5'])), /refused in offline mode/);
  });

  test('search commands take their query only through --query', () => {
    for (const command of ['citation-search', 'scholar-search', 's2-search']) {
      assert.match(errorOf(run([command, 'positional query'])), /takes its query through --query/, command);
    }
  });
} finally {
  fs.rmSync(scratch, { recursive: true, force: true });
}

console.log(`\n${passed} tool dispatcher contracts passed`);
