#!/usr/bin/env node
'use strict';

<!-- Generated by WTF-P adapter compiler v5 from protocol/tools.json; do not edit. -->

// Single bounded entry point for every WTF-P bundled tool. Usage:
//   node <package-root>/tools/wtfp-tool.js <command> [arguments]
// Every command prints one JSON document on stdout. Failures print
// {"error": "..."} on stderr and exit 1. No other module in this package is
// intended to be executed directly.

const fs = require('fs');

const MODULES = {
  "bibliography.index": "./bibliography/index.js",
  "bibliography.format": "./bibliography/format.js",
  "bibliography.analyze-impact": "./bibliography/analyze-impact.js",
  "citation.fetch": "./citation/fetch.js",
  "citation.scholar-lookup": "./citation/scholar-lookup.js",
  "citation.semantic-scholar": "./citation/semantic-scholar.js",
  "citation.rank": "./citation/rank.js"
};

const COMMANDS = [
  {
    "command": "bib-index",
    "tool": "bibliography.index",
    "usage": "bib-index <bib-file> [--key=<citation-key>] [--query=<text>]"
  },
  {
    "command": "bib-format",
    "tool": "bibliography.format",
    "usage": "bib-format <bib-file> --key=<citation-key>"
  },
  {
    "command": "bib-impact",
    "tool": "bibliography.analyze-impact",
    "usage": "bib-impact <bib-file>"
  },
  {
    "command": "citation-search",
    "tool": "citation.fetch",
    "usage": "citation-search --query=<text> [--limit=<1-25>] [--intent=<seminal|recent|balanced>] [--year=<yyyy>]"
  },
  {
    "command": "scholar-search",
    "tool": "citation.scholar-lookup",
    "usage": "scholar-search --query=<text> [--limit=<1-25>]"
  },
  {
    "command": "s2-search",
    "tool": "citation.semantic-scholar",
    "usage": "s2-search --query=<text> [--limit=<1-25>] [--year=<yyyy>]"
  },
  {
    "command": "rank",
    "tool": "citation.rank",
    "usage": "rank <papers.json> [--intent=<seminal|recent|balanced>]"
  }
];

const MAX_QUERY = 512;
const MAX_LIMIT = 25;

function fail(message) {
  process.stderr.write(`${JSON.stringify({ error: message })}\n`);
  process.exit(1);
}

function emit(value) {
  process.stdout.write(`${JSON.stringify(value, null, 2)}\n`);
}

function parseArguments(argv) {
  const flags = new Map();
  const positional = [];
  for (const argument of argv) {
    const flag = /^--([a-z][a-z0-9-]*)=([\s\S]*)$/.exec(argument);
    if (flag) {
      if (flags.has(flag[1])) fail(`repeated flag: --${flag[1]}`);
      flags.set(flag[1], flag[2]);
    } else if (argument.startsWith('--')) {
      fail(`unsupported flag syntax: ${argument}`);
    } else {
      positional.push(argument);
    }
  }
  return { flags, positional };
}

function requireText(value, label) {
  if (typeof value !== 'string' || value.trim().length === 0) fail(`missing ${label}`);
  if (value.length > MAX_QUERY) fail(`${label} exceeds ${MAX_QUERY} characters`);
  return value;
}

function readTextFile(candidate) {
  const file = requireText(candidate, 'file path');
  let stat;
  try {
    stat = fs.lstatSync(file);
  } catch {
    fail(`file not found: ${file}`);
  }
  if (!stat.isFile()) fail(`not a regular file: ${file}`);
  return fs.readFileSync(file, 'utf8');
}

function limitOf(flags) {
  if (!flags.has('limit')) return 10;
  const limit = Number.parseInt(flags.get('limit'), 10);
  if (!Number.isInteger(limit) || limit < 1 || limit > MAX_LIMIT) fail(`--limit must be an integer between 1 and ${MAX_LIMIT}`);
  return limit;
}

function intentOf(flags) {
  const intent = flags.get('intent') || 'balanced';
  if (!['seminal', 'recent', 'balanced'].includes(intent)) fail('--intent must be seminal, recent, or balanced');
  return intent;
}

function yearOf(flags) {
  if (!flags.has('year')) return null;
  const year = flags.get('year');
  if (!/^\d{4}$/.test(year)) fail('--year must be a four-digit year');
  return year;
}

async function main(argv) {
  const command = argv[0];
  if (!command || command === 'list' || command === '--help' || command === '-h') {
    emit({ tool: 'wtfp-tool', commands: COMMANDS });
    return;
  }
  const declared = COMMANDS.find((entry) => entry.command === command);
  if (!declared) fail(`unknown command: ${command}; run \`list\` for the declared set`);
  const { flags, positional } = parseArguments(argv.slice(1));
  if (positional.length > 1) fail(`${command} accepts at most one positional argument: ${declared.usage}`);
  const load = () => require(MODULES[declared.tool]);

  if (command === 'bib-index') {
    const content = readTextFile(positional[0]);
    const bib = load();
    if (flags.has('key')) {
      const key = requireText(flags.get('key'), '--key');
      const entry = bib.getEntry(content, key);
      if (entry === null) fail(`citation key not found: ${key}`);
      return emit({ key, entry });
    }
    if (flags.has('query')) return emit(JSON.parse(bib.search(content, requireText(flags.get('query'), '--query'))));
    return emit(JSON.parse(bib.index(content)));
  }
  if (command === 'bib-format') {
    const content = readTextFile(positional[0]);
    const key = requireText(flags.get('key'), '--key');
    const entry = require(MODULES['bibliography.index']).getEntry(content, key);
    if (entry === null) fail(`citation key not found: ${key}`);
    const formatter = load();
    return emit({ key, formatted: formatter.format(formatter.parse(entry)) });
  }
  if (command === 'bib-impact') {
    const file = requireText(positional[0], 'file path');
    readTextFile(file);
    return emit(await load().analyze(file));
  }
  if (command === 'citation-search') {
    const query = requireText(flags.get('query') || positional[0], '--query');
    const year = yearOf(flags);
    return emit(await load().search(query, { limit: limitOf(flags), intent: intentOf(flags), ...(year ? { year } : {}) }));
  }
  if (command === 'scholar-search') {
    const query = requireText(flags.get('query') || positional[0], '--query');
    return emit(await load().search(query, { limit: limitOf(flags) }));
  }
  if (command === 's2-search') {
    const query = requireText(flags.get('query') || positional[0], '--query');
    const year = yearOf(flags);
    return emit(await load().search(query, { limit: limitOf(flags), ...(year ? { year } : {}) }));
  }
  if (command === 'rank') {
    const papers = JSON.parse(readTextFile(positional[0]));
    if (!Array.isArray(papers)) fail('rank expects a JSON array of paper records');
    return emit(load().rank(papers, intentOf(flags)));
  }
  fail(`unimplemented command: ${command}`);
}

main(process.argv.slice(2)).catch((error) => fail(error && error.message ? error.message : String(error)));
