#!/usr/bin/env node
'use strict';

// Generated by WTF-P adapter compiler v5 from protocol/tools.json; do not edit.

// Single bounded entry point for every WTF-P bundled tool. Usage:
//   node <package-root>/tools/wtfp-tool.js [--offline] <command> [arguments]
//   node <package-root>/tools/wtfp-tool.js <command> --help
// Every command prints one JSON document on stdout. Failures print
// {"error": "..."} on stderr and exit 1; a network command that exceeds its
// --timeout (default 20 s) exits 124. Each declared command carries its
// effects; --offline or WTFP_TOOL_OFFLINE=1 refuses any command whose effects
// include network.*. No other module in this package is intended to be
// executed directly.

const fs = require('fs');

const MODULES = {
  "bibliography.index": "./bibliography/index.js",
  "bibliography.format": "./bibliography/format.js",
  "bibliography.analyze-impact": "./bibliography/analyze-impact.js",
  "citation.fetch": "./citation/fetch.js",
  "citation.scholar-lookup": "./citation/scholar-lookup.js",
  "citation.semantic-scholar": "./citation/semantic-scholar.js",
  "citation.rank": "./citation/rank.js"
};

const COMMANDS = [
  {
    "command": "bib-index",
    "tool": "bibliography.index",
    "usage": "bib-index <bib-file> [--key=<citation-key>] [--query=<text>]",
    "effects": [
      "filesystem.read"
    ]
  },
  {
    "command": "bib-format",
    "tool": "bibliography.format",
    "usage": "bib-format <bib-file> --key=<citation-key> [--style=<bibtex|al-folio>]",
    "effects": [
      "filesystem.read"
    ]
  },
  {
    "command": "bib-impact",
    "tool": "bibliography.analyze-impact",
    "usage": "bib-impact <bib-file> [--timeout=<seconds>]",
    "effects": [
      "filesystem.read",
      "network.search"
    ]
  },
  {
    "command": "citation-search",
    "tool": "citation.fetch",
    "usage": "citation-search --query=<text> [--backend=<legacy|cite-nexus>] [--providers=<comma-separated-IDs>] [--limit=<1-25>] [--intent=<seminal|recent|balanced>] [--year=<yyyy>] [--timeout=<seconds>]",
    "effects": [
      "network.search"
    ]
  },
  {
    "command": "scholar-search",
    "tool": "citation.scholar-lookup",
    "usage": "scholar-search --query=<text> [--limit=<1-25>] [--timeout=<seconds>]",
    "effects": [
      "network.search"
    ]
  },
  {
    "command": "s2-search",
    "tool": "citation.semantic-scholar",
    "usage": "s2-search --query=<text> [--limit=<1-25>] [--year=<yyyy>] [--timeout=<seconds>]",
    "effects": [
      "network.fetch",
      "network.search"
    ]
  },
  {
    "command": "rank",
    "tool": "citation.rank",
    "usage": "rank <papers.json> [--intent=<seminal|recent|balanced>]",
    "effects": []
  }
];

const MAX_QUERY = 512;
const MAX_PATH = 4096;
const MAX_LIMIT = 25;
const DEFAULT_TIMEOUT_SECONDS = 20;
const MAX_TIMEOUT_SECONDS = 600;
const EXIT_TIMEOUT = 124;

function offlineRequested(argv) {
  const flag = process.env.WTFP_TOOL_OFFLINE;
  return argv.includes('--offline') || flag === '1' || flag === 'true';
}

function fail(message, status = 1) {
  process.stderr.write(`${JSON.stringify({ error: message })}\n`);
  process.exit(status);
}

function emit(value) {
  process.stdout.write(`${JSON.stringify(value, null, 2)}\n`);
}

function parseArguments(argv) {
  const flags = new Map();
  const positional = [];
  for (const argument of argv) {
    const flag = /^--([a-z][a-z0-9-]*)=([\s\S]*)$/.exec(argument);
    if (flag) {
      if (flags.has(flag[1])) fail(`repeated flag: --${flag[1]}`);
      flags.set(flag[1], flag[2]);
    } else if (argument.startsWith('--')) {
      fail(`unsupported flag syntax: ${argument}`);
    } else {
      positional.push(argument);
    }
  }
  return { flags, positional };
}

function requireText(value, label) {
  if (typeof value !== 'string' || value.trim().length === 0) fail(`missing ${label}`);
  if (value.length > MAX_QUERY) fail(`${label} exceeds ${MAX_QUERY} characters`);
  return value;
}

// The caller names the file and the process runs with the caller's own
// privileges, so there is no boundary to contain a path within: a symlink can
// reach nothing the caller could not name directly. The realpath is resolved
// first so a symlinked .bib is accepted; the resolved target must be a regular
// file and is read by its resolved name.
function readTextFile(candidate) {
  const file = requirePath(candidate);
  let resolved;
  try {
    resolved = fs.realpathSync(file);
  } catch {
    fail(`file not found: ${file}`);
  }
  if (!fs.statSync(resolved).isFile()) fail(`not a regular file: ${file}`);
  return fs.readFileSync(resolved, 'utf8');
}

function requirePath(candidate) {
  if (typeof candidate !== 'string' || candidate.trim().length === 0) fail('missing file path');
  if (candidate.length > MAX_PATH) fail(`file path exceeds ${MAX_PATH} characters`);
  return candidate;
}

function timeoutOf(flags) {
  if (!flags.has('timeout')) return DEFAULT_TIMEOUT_SECONDS;
  const seconds = /^\d+$/.test(flags.get('timeout')) ? Number(flags.get('timeout')) : NaN;
  if (!Number.isInteger(seconds) || seconds < 1 || seconds > MAX_TIMEOUT_SECONDS) {
    fail(`--timeout must be an integer number of seconds between 1 and ${MAX_TIMEOUT_SECONDS}`);
  }
  return seconds;
}

// Hard wall clock for a network command: report on stderr and exit 124. A
// hung socket cannot keep the process alive past this point.
function withTimeout(promise, seconds, command) {
  const timer = setTimeout(() => {
    process.stderr.write(`${JSON.stringify({ error: `${command} timed out after ${seconds} s` })}\n`);
    process.exit(EXIT_TIMEOUT);
  }, seconds * 1000);
  return promise.finally(() => clearTimeout(timer));
}

function progress(message) {
  process.stderr.write(`${message}\n`);
}

// A key that appears more than once cannot be selected by name.
function uniqueEntry(bib, content, key) {
  const matches = bib.findEntries(content, key);
  if (matches.length === 0) fail(`citation key not found: ${key}`);
  if (matches.length > 1) fail(`citation key is ambiguous: ${key} appears ${matches.length} times; deduplicate the file first`);
  return matches[0];
}

function limitOf(flags) {
  if (!flags.has('limit')) return 10;
  const limit = /^\d+$/.test(flags.get('limit')) ? Number(flags.get('limit')) : NaN;
  if (!Number.isInteger(limit) || limit < 1 || limit > MAX_LIMIT) fail(`--limit must be an integer between 1 and ${MAX_LIMIT}`);
  return limit;
}

function intentOf(flags) {
  const intent = flags.get('intent') || 'balanced';
  if (!['seminal', 'recent', 'balanced'].includes(intent)) fail('--intent must be seminal, recent, or balanced');
  return intent;
}

function yearOf(flags) {
  if (!flags.has('year')) return null;
  const year = flags.get('year');
  if (!/^\d{4}$/.test(year)) fail('--year must be a four-digit year');
  return year;
}

async function main(rawArgv) {
  const offline = offlineRequested(rawArgv);
  const argv = rawArgv.filter((argument) => argument !== '--offline');
  const command = argv[0];
  if (!command || command === 'list' || command === '--help' || command === '-h') {
    emit({ tool: 'wtfp-tool', offline, commands: COMMANDS });
    return;
  }
  const declared = COMMANDS.find((entry) => entry.command === command);
  if (!declared) fail(`unknown command: ${command}; run \`list\` for the declared set`);
  if (argv.slice(1).some((argument) => argument === '--help' || argument === '-h')) {
    emit(declared);
    return;
  }
  const networkEffects = declared.effects.filter((effect) => effect.startsWith('network.'));
  if (offline && networkEffects.length > 0) {
    fail(`${command} is refused in offline mode: it declares ${networkEffects.join(', ')}`);
  }
  const { flags, positional } = parseArguments(argv.slice(1));
  const allowedFlags = {
    'bib-index': ['key', 'query'], 'bib-format': ['key', 'style'],
    'bib-impact': ['timeout'], 'citation-search': ['query', 'backend', 'providers', 'limit', 'intent', 'year', 'timeout'],
    'scholar-search': ['query', 'limit', 'timeout'], 's2-search': ['query', 'limit', 'year', 'timeout'],
    'rank': ['intent']
  };
  for (const key of flags.keys()) if (!allowedFlags[command].includes(key)) fail(`unknown --${key} for ${command}`);
  if (positional.length > 1) fail(`${command} accepts at most one positional argument: ${declared.usage}`);
  const load = () => require(MODULES[declared.tool]);

  if (command === 'bib-index') {
    const content = readTextFile(positional[0]);
    const bib = load();
    if (flags.has('key')) {
      const key = requireText(flags.get('key'), '--key');
      return emit({ key, entry: uniqueEntry(bib, content, key) });
    }
    if (flags.has('query')) return emit(JSON.parse(bib.search(content, requireText(flags.get('query'), '--query'))));
    return emit({ entries: JSON.parse(bib.index(content)), duplicates: bib.duplicateKeys(content) });
  }
  if (command === 'bib-format') {
    const content = readTextFile(positional[0]);
    const key = requireText(flags.get('key'), '--key');
    const style = flags.get('style') || 'bibtex';
    if (!['bibtex', 'al-folio'].includes(style)) fail('--style must be bibtex or al-folio');
    const entry = uniqueEntry(require(MODULES['bibliography.index']), content, key);
    const formatter = load();
    return emit({ key, style, formatted: formatter.format(formatter.parse(entry), {}, { style }) });
  }
  if (command === 'bib-impact') {
    const file = requirePath(positional[0]);
    readTextFile(file);
    const seconds = timeoutOf(flags);
    const onProgress = (done, total) => progress(`bib-impact: ${done}/${total} entries queried`);
    return emit(await withTimeout(load().analyze(file, { onProgress }), seconds, command));
  }
  if (command === 'citation-search') {
    if (positional.length > 0) fail(`${command} takes its query through --query: ${declared.usage}`);
    const query = requireText(flags.get('query'), '--query');
    const year = yearOf(flags);
    const seconds = timeoutOf(flags);
    const backend = flags.get('backend') || 'legacy';
    if (!['legacy', 'cite-nexus'].includes(backend)) fail('--backend must be legacy or cite-nexus');
    const providers = flags.has('providers') ? flags.get('providers').split(',').map((p) => p.trim()) : undefined;
    if (providers && backend !== 'cite-nexus') fail('--providers requires --backend=cite-nexus');
    return emit(await withTimeout(load().search(query, { backend, providers, timeoutSeconds: seconds, limit: limitOf(flags), intent: intentOf(flags), ...(year ? { year } : {}) }), seconds, command));
  }
  if (command === 'scholar-search') {
    if (positional.length > 0) fail(`${command} takes its query through --query: ${declared.usage}`);
    const query = requireText(flags.get('query'), '--query');
    const seconds = timeoutOf(flags);
    return emit(await withTimeout(load().search(query, { limit: limitOf(flags) }), seconds, command));
  }
  if (command === 's2-search') {
    if (positional.length > 0) fail(`${command} takes its query through --query: ${declared.usage}`);
    const query = requireText(flags.get('query'), '--query');
    const year = yearOf(flags);
    const seconds = timeoutOf(flags);
    return emit(await withTimeout(load().search(query, { limit: limitOf(flags), ...(year ? { year } : {}) }), seconds, command));
  }
  if (command === 'rank') {
    const papers = JSON.parse(readTextFile(positional[0]));
    if (!Array.isArray(papers)) fail('rank expects a JSON array of paper records');
    return emit(load().rank(papers, intentOf(flags)));
  }
  fail(`unimplemented command: ${command}`);
}

// Run only as an entry point. OpenCode imports every `tools/*.js` below its
// config root as a custom-tool module; an unconditional main() printed a
// dispatcher error and exited the host process at session start.
if (require.main === module) {
  main(process.argv.slice(2)).catch((error) => fail(error && error.message ? error.message : String(error), error && error.code === 'WTFP_TIMEOUT' ? EXIT_TIMEOUT : 1));
}
